### PR TITLE
Additional Tests for api gw, large swagger file, and invalid swagger file

### PR DESCRIPTION
**Pull request by nwspeete-ibm**
- large swagger file
   - multiple path/endpoints
- invalid swagger file

### CODE REVIEW

**Comment by markusthoemmes** [comment]
What is a "complex" swagger file supposed to test? Are all the small functionalities tested for themselves?

**Comment by nwspeete-ibm** [comment]
Complex swagger file tests for more than 1 path.

**Comment by nwspeete-ibm** [comment]
pg build on pg1 /1​12​1

**Comment by csantanapr** [comment]
@mdeuser could you review latest changes, I added you as a reviewer.

**Comment by csantanapr** [comment]
@mdeuser can you give it another review, and open issues for the none blocking review comments to be done later.

**Comment by mdeuser** [comment]
@csantanapr - review comments are still applicable; no new commits since the last review.  Issue #1817 has been opened to address outstanding comments.

**Comment by csantanapr** [comment]
This PR is superseded by #1818 @mdeuser working on it now.

**Pull request closed without merging**
