### PR TITLE
Using zookeeper image from Dockerhub

### PR DESCRIPTION
**Pull request by markusthoemmes**
- adjusted redo
- removed own Dockerfile

### CODE REVIEW

**Comment by rabbah** [comment]
missed:

              'build/deploy kafka (includes zookeeper)',

(comment out of date)
and

    makeComponent('zookeeper',
                  'build zookeeper only (to deploy, use kakfa component)',
                  yaml = False,
                  gradle = ':services:zookeeper'),

will fail with redo zookeeper

**Comment by rabbah** [comment]
image is ~61% smaller :+1: 

missed:

              'build/deploy kafka (includes zookeeper)',

(comment out of date)
and

    makeComponent('zookeeper',
                  'build zookeeper only (to deploy, use kakfa component)',
                  yaml = False,
                  gradle = ':services:zookeeper'),

will fail with `redo zookeeper` (no longer needed, can just docker pull).

i'll remove/patch this on merge.
is there a pg?

**Comment by markusthoemmes** [comment]
Thanks for catching @rr, PG2 176 approved

**Comment by rabbah** [comment]
Merged as https://github.com/openwhisk/openwhisk/commit/f2ad87c54ab65c8e184e52ffc50a7454bbb3e885.

**Pull request closed without merging**
