### PR TITLE
Treat error field differently if present in the initial payload to a sequence

### PR DESCRIPTION
**Pull request by ioana-blue**
Update test accordingly.

This is a fix for #1822 

Note that I left the scanLeft unchanged. I'd rather do the "optimization" refactoring in a different pass since it's  a lot more involved than current change. I'm guessing we'd like to promote this change soonish.

### CODE REVIEW

**Comment by ioana-blue** [comment]
PG2 1033

**Comment by starpit** [comment]
i still think its dangerous ever to look at inputs. these are out of control of the action for several reasons. you are protecting against one, now -- data from the outside world.

the other potential source of inputs is package bindings. wouldn't it be odd behavior if, on day N, the team adds a package parameter named `error`, and their app suddenly stops working?

**Comment by ioana-blue** [comment]
@starpit not sure I understand your comment above. IIRC package bindings are merged in the input params of the actions. After this is PR is merged in, the input parameters are *not* filtered for error, so nothing would break.

**Comment by rabbah** [comment]
I'll accept this patch but this change highlights how the sequence implementation should be done with a state machine/akka actor. This will have the added benefit of reducing the state held in flight to just the "last" activation result.

**Comment by ioana-blue** [comment]
PG3 419

**Pull request merged**
