### PR TITLE
improve isAlive method for zookeeper, kafka

### PR DESCRIPTION
**Pull request by lehoanganh**
As per title.

### CODE REVIEW

**Comment by lehoanganh** [comment]
For debug:

```
TASK [invoker : wait until Invoker is up and running] **************************
Thursday 30 June 2016  11:05:33 +0200 (0:00:00.572)       0:00:48.572 ********* 
FAILED - RETRYING: TASK: invoker : wait until Invoker is up and running (11 retries left).
ok: [172.17.0.1]

TASK [invoker : debug] *********************************************************
Thursday 30 June 2016  11:05:39 +0200 (0:00:05.346)       0:00:53.918 ********* 
ok: [172.17.0.1] => {
    "result": {
        "changed": false, 
        "connection": "close", 
        "content_length": "4", 
        "content_type": "text/plain; charset=UTF-8", 
        "date": "Thu, 30 Jun 2016 09:05:39 GMT", 
        "msg": "OK (4 bytes)", 
        "redirected": false, 
        "server": "spray-can/1.3.3", 
        "status": 200, 
        "url": "http://172.17.0.1:12001/ping"
    }
}
```

```
TASK [controller : wait until the Controller in this host is up and running] ***
Thursday 30 June 2016  11:05:26 +0200 (0:00:00.543)       0:00:41.763 ********* 
FAILED - RETRYING: TASK: controller : wait until the Controller in this host is up and running (11 retries left).
ok: [172.17.0.1]

TASK [controller : debug] ******************************************************
Thursday 30 June 2016  11:05:32 +0200 (0:00:05.400)       0:00:47.164 ********* 
ok: [172.17.0.1] => {
    "result": {
        "changed": false, 
        "connection": "close", 
        "content_length": "4", 
        "content_type": "text/plain; charset=UTF-8", 
        "date": "Thu, 30 Jun 2016 09:05:32 GMT", 
        "msg": "OK (4 bytes)", 
        "redirected": false, 
        "server": "spray-can/1.3.3", 
        "status": 200, 
        "url": "http://172.17.0.1:10001/ping"
    }
}
```

```
TASK [kafka : wait until the Kafka in this host is up and running] *************
Thursday 30 June 2016  11:04:59 +0200 (0:00:00.654)       0:00:14.726 ********* 
FAILED - RETRYING: TASK: kafka : wait until the Kafka in this host is up and running (11 retries left).
FAILED - RETRYING: TASK: kafka : wait until the Kafka in this host is up and running (10 retries left).
FAILED - RETRYING: TASK: kafka : wait until the Kafka in this host is up and running (9 retries left).
FAILED - RETRYING: TASK: kafka : wait until the Kafka in this host is up and running (8 retries left).
FAILED - RETRYING: TASK: kafka : wait until the Kafka in this host is up and running (7 retries left).
ok: [172.17.0.1]

TASK [kafka : debug] ***********************************************************
Thursday 30 June 2016  11:05:25 +0200 (0:00:25.871)       0:00:40.598 ********* 
ok: [172.17.0.1] => {
    "result": {
        "changed": false, 
        "connection": "close", 
        "content_length": "13", 
        "content_type": "application/json; charset=utf-8", 
        "date": "Thu, 30 Jun 2016 09:05:25 GMT", 
        "etag": "W/\"d-YEND/2CgAzUvwb+FX/mnwA\"", 
        "json": {
            "msg": "yes"
        }, 
        "msg": "OK (13 bytes)", 
        "redirected": false, 
        "status": 200, 
        "url": "http://172.17.0.1:9093/ready", 
        "x_powered_by": "Express"
    }
}
```

```
TASK [kafka : wait before checking if zookeeper is up] *************************
Thursday 30 June 2016  11:04:56 +0200 (0:00:00.613)       0:00:11.744 ********* 
Pausing for 2 seconds
(ctrl+C then 'C' = continue early, ctrl+C then 'A' = abort)
ok: [172.17.0.1]

TASK [kafka : debug] ***********************************************************
Thursday 30 June 2016  11:04:58 +0200 (0:00:02.038)       0:00:13.782 ********* 
ok: [172.17.0.1] => {
    "result": {
        "changed": false, 
        "connection": "close", 
        "content_length": "4", 
        "content_type": "application/json", 
        "date": "Thu, 30 Jun 2016 09:04:54 GMT", 
        "json": true, 
        "msg": "OK (4 bytes)", 
        "redirected": false, 
        "status": 200, 
        "url": "http://172.17.0.1:8500/v1/kv/consulIsAlive"
    }
}
```

```
TASK [consul : wait until the Consul Server/Agent in this host is up and running] ***
Thursday 30 June 2016  11:04:49 +0200 (0:00:00.997)       0:00:03.822 ********* 
FAILED - RETRYING: TASK: consul : wait until the Consul Server/Agent in this host is up and running (11 retries left).
ok: [172.17.0.1]

TASK [consul : debug] **********************************************************
Thursday 30 June 2016  11:04:54 +0200 (0:00:05.366)       0:00:09.188 ********* 
ok: [172.17.0.1] => {
    "result": {
        "changed": false, 
        "connection": "close", 
        "content_length": "4", 
        "content_type": "application/json", 
        "date": "Thu, 30 Jun 2016 09:04:54 GMT", 
        "json": true, 
        "msg": "OK (4 bytes)", 
        "redirected": false, 
        "status": 200, 
        "url": "http://172.17.0.1:8500/v1/kv/consulIsAlive"
    }
}
```

**Comment by lehoanganh** [comment]
IPG 219 green

**Comment by psuter** [comment]
The changes look good to me. Are we waiting for one thumb up per assignee? Happy to squash and merge after that.

**Comment by lehoanganh** [comment]
squashed.

**Pull request merged**
