### PR TITLE
Dockerfile changed to Swift 3.0.2

### PR DESCRIPTION
**Pull request by Averylamp**
Fixes Issue #1712 
Update from Swift 3.0.1 to Swift 3.0.2
PG2 872

### CODE REVIEW

**Comment by csantanapr** [comment]
@Averylamp Thanks for your contribution to Apache OpenWhisk.

The project policy is that request to all contributors to submit an Apache iCLA for the Apache OpenWhisk project.
Please follow the steps [here](https://www.apache.org/licenses/icla.txt), and let me know once you received confirmation of submission

**Comment by rabbah** [comment]
@csantanapr we need a CLA even for a change this small?

**Comment by csantanapr** [comment]
Usually is always good to ask politely for CLA.
If person doesn't do it for what ever reason in 1 or 2 days and it's not a significant change, I would just merge the PR.

This get's people walking down the process to contribute more. Also if we don't ask for CLA and accept, and have seeing the case where the person will submit a second PR with more significant changes and if we then ask for an CLA then they complaint that the first PR we didn't ask for CLA.

I thought @paulcastro was going to merge days ago.
I will merge now I guess.

**Comment by csantanapr** [comment]
rebase and merged 3258a1fe4735cc1ce4143201b57aa0063c40fd17

**Comment by rabbah** [comment]
Thanks for the explanation.

**Pull request closed without merging**
