### PR TITLE
increase nginx worker connections

### PR DESCRIPTION
**Pull request by xin-cai**
increase nginx worker connections and change worker processes to auto

### CODE REVIEW

**Comment by xin-cai** [comment]
PG4/202 is running

**Comment by markusthoemmes** [comment]
Can you elaborate on this change? What are we expecting to change since you bumped the connection by quite little.

**Comment by xin-cai** [comment]
reset `worker_connections` back to `4096` to minimize the impact,  the new configuration of `worker_processes auto` can already increase the nginx capacity


```
worker_processes – The number of NGINX worker processes (the default is 1). In most cases, running one worker process per CPU core works well, and we recommend setting this directive to auto to achieve that. There are times when you may want to increase this number, such as when the worker processes have to do a lot of disk I/O.
```

**Comment by xin-cai** [comment]
PG4/203 is green

**Comment by xin-cai** [comment]
dup with https://github.com/openwhisk/openwhisk/pull/2233, close this one

**Pull request closed without merging**
