### PR TITLE
Tighten container reclamation.

### LINKED ISSUE #1554: Invoker should dispense with container if it times out on "run"
The invoker will currently attempt to reuse a container even if a previous run of an action inside that same container timed out - this should be treated as a failed activation and the container reclaimed instead.

### PR DESCRIPTION
**Pull request by rabbah**
If the result of running an action in the container is not successful, delete the container. Makes this is true for both failed init and run.

Fixes #1554 but need to engineer a proper test.

### CODE REVIEW

**Comment by rabbah** [comment]
test added.
pg1/1035.

**Comment by perryibm** [comment]
LGTM.  One question, is the precise text of the timed out case part of the contract?

**Comment by rabbah** [comment]
Yes - admittedly I was lazy this time and didn't move this to the `Messages` singleton where I've incrementally accumulated the error responses. At your insistence, I'll do that.

**Comment by perryibm** [comment]
Either that or inline a comment in the test case so that if there is a discrepancy (we'll eventually change wording or internationalize), whoever gets the bug will have a clue.

**Comment by rabbah** [comment]
thanks for the nudge; addressed in latest commit.

**Comment by perryibm** [comment]
Can you fix the conflict in ErrorResponse?

**Comment by rabbah** [comment]
rebased.

**Comment by rabbah** [comment]
Merged as https://github.com/openwhisk/openwhisk/commit/64531db21363a709f73f97b8bbd6a0f9e55425f0.

**Pull request closed without merging**
