### PR TITLE
WIP - Addition of install for push notifications package.

### PR DESCRIPTION
**Pull request by nwspeete-ibm**

### CODE REVIEW

**Comment by rabbah** [comment]
Should this be in openwhisk at all?

**Comment by mrutkows** [comment]
IMO, the question for this package, like a few others in various stages of progress, is it something that is considered an essential package that would/could be leveraged by a many customer/user scenarios or demos; if so, then they should be installed as part of the "core" system to make it useful (apart from system, utils) out-of-the-box.

**Comment by rabbah** [comment]
we should document the `git clone` and `install.sh` steps for external packages and not install them. this is creating a core dependence on external packages.

core packages are ones we will continue to provide in whisk.system, do you disagree?

**Comment by nwspeete-ibm** [comment]
So the course of action should be to document the installation steps for open (not deliver the .sh files to open at all). The installation steps will be: 1. Run git clone https://github.com/openwhisk/wsk-pkg-pushnotifications.git "$dir" 2. Run the install.sh script from the clone

**Comment by rabbah** [comment]
@nwspeete-ibm is this still a valid PR?

**Comment by nwspeete-ibm** [comment]
The steps are documented in the push package and open on how to install. This is no longer a valid PR because of the decision to have git clone and install.sh steps for external packages.

**Pull request closed without merging**
