### PR TITLE
Update Swift’s Whisk.invoke() to support non-blocking invocations

### PR DESCRIPTION
**Pull request by akrabat**
Add a third parameter, `blocking`, to invoke() to enable non-blocking invocations. Default to `blocking=true` for BC.

### CODE REVIEW

**Comment by bjustin-ibm** [comment]
Neato! We should probably add a test for this though.

**Comment by akrabat** [comment]
> Neato! We should probably add a test for this though.

Will do.

**Comment by akrabat** [comment]
@bjustin-ibm Test added :)

**Comment by bjustin-ibm** [comment]
@paulcastro any changes to make before I merge this?

**Comment by paulcastro** [comment]
Go for it

**Comment by rabbah** [comment]
needs a pg since swift tests dont run in travis.

**Comment by paulcastro** [comment]
@rr  pg85 in progress

**Comment by paulcastro** [comment]
pg build failure, probably a deployment issue.  Let's rebase on master first and I can try again.

**Comment by rabbah** [comment]
@bjustin-ibm what's status on this?

**Comment by bjustin-ibm** [comment]
@rabbah Last comment was:
> pg build failure, could be a deployment issue. Let's rebase on master first and I can try again.

**Comment by rabbah** [comment]
pg2/1413 🏃

**Comment by rabbah** [comment]
pg approved.

**Comment by rabbah** [comment]
Rebased, squashed and merged as https://github.com/openwhisk/openwhisk/commit/8b7e3929e3168095e10e345a67d784871a2b46ba.

**Comment by akrabat** [comment]
Thanks for merging. Can the Docker container be updated too please?

**Comment by rabbah** [comment]
It should already be. The images are populated automatically now thanks to @csantana.

**Comment by akrabat** [comment]
You're right. Sorry. I was using the wrong image…

**Pull request closed without merging**
