### PR TITLE
Modify tools/db/README.md

### PR DESCRIPTION
**Pull request by daisy-ycguo**
Add a statement to explain how to create `local_db.ini` if it doesn't exist.

### CODE REVIEW

**Comment by daisy-ycguo** [comment]
@csantanapr I try to install OpenWhisk on my Ubuntu natively. When I'm trying to configure db following the description in tools/db/README.md, I find there is no `local_db.ini` in folder `openwhisk/ansible`. It took me a few minutes to find how to create this file. So I think we should clearly document it in `tools/db/README.md`.

**Comment by csantanapr** [comment]
Sure submit a PR

**Comment by csantanapr** [comment]
LGTM

**Comment by csantanapr** [comment]
rebase and merged with fc2d684cf88f7c7387a345a0abd9ab6128bf7f13

**Pull request closed without merging**
