### PR TITLE
Allow JSON to be Input from a File

### PR DESCRIPTION
**Pull request by dubeejw**
- Pass JSON files to parameters and annotations
  - Add tests to ensure file input works as desired
- Refactor parameter and annotation handling
  - Use KeyValueArr data type to store annotations and parameters
- Refactor summaries for get commands
  - Use KeyValueArr data type to get annotations and parameters
- Refactor parameter and annotation tests
  - Order of params and annots are not guaranteed in Go map data structures
- Fixes: #426

### CODE REVIEW

**Comment by dubeejw** [comment]
PG1 554

**Comment by dubeejw** [comment]
@mdeuser, can you review this?

**Comment by dubeejw** [comment]
PG2 265.

**Comment by mdeuser** [comment]
Code walkthrough with @dubeejw complete.  A couple small code changes were identified and noted as code comments.

**Comment by dubeejw** [comment]
@markusthoemmes, thanks for the suggestion. I like the naming conventions you mentioned better.

**Comment by dubeejw** [comment]
PG1 609.

**Comment by dubeejw** [comment]
@rabbah, can you look over this? Mark and I say down, and went through the code. He's on vacation now though.

**Comment by dubeejw** [comment]
@mdeuser, any other comments on this one?

**Comment by mdeuser** [comment]
@dubeejw - I think we covered all my comments in our code walk-through.  One point we discussed was re: `KeyValues`; that this was no longer used and should be removed.  Is that still the case?

**Comment by dubeejw** [comment]
@mdeuser, forgot to delete that one. Should be ready to go now.

**Comment by mdeuser** [comment]
LGTM

**Comment by dubeejw** [comment]
@csantanapr, please merge.

**Comment by bjustin-ibm** [comment]
PG2 410

**Pull request merged**
