### PR TITLE
Add twilio node sdk

### PR DESCRIPTION
**Pull request by saschoff91**
For enabling twilio service for openwhisk, the sdk is required.

### CODE REVIEW

**Comment by csantanapr** [comment]
Update the docs also here [docs/reference.md](https://github.com/openwhisk/openwhisk/blob/master/docs/reference.md#runtime-environment)

**Comment by rabbah** [comment]
@csantanapr @saschoff91 while at it, shall we add http://stackoverflow.com/questions/37887584/using-iconv-in-bluemixs-openwhisk

**Comment by csantanapr** [comment]
@rabbah sure and also update  watson-developer-cloud to latest I think @l2fprod wanted this.

**Comment by l2fprod** [comment]
How about pkgcloud too for all things openstack (mainly swift storage)?

**Comment by csantanapr** [comment]
Hi @l2fprod this one? https://www.npmjs.com/package/pkgcloud

**Comment by l2fprod** [comment]
@csantanapr yes

**Comment by csantanapr** [comment]
Added all the other packages here #829 
Also I think we should leave node 0.12 untouch and just update node6

**Comment by csantanapr** [comment]
superseded it by #829

**Pull request closed without merging**
