### PR TITLE
update and add npm packages to nodejs6 actions supercede #774

### PR DESCRIPTION
**Pull request by csantanapr**
add twilio sendgrid pkgcloud iconv-lite
update watson-developer cloud

### CODE REVIEW

**Comment by csantanapr** [comment]
IPG 238 queued

**Comment by bjustin-ibm** [comment]
@csantanapr This requires a doc update as well, right?

**Comment by csantanapr** [comment]
Ah shoot, please update docs for me :-)

**Comment by csantanapr** [comment]
Well you need to update the docs for all nodejs6 npm packages. Please create a table that list nose 0.12 and 6 since the list is different and they should have versions for the npm packages.

**Comment by csantanapr** [comment]
@bjustin-ibm you can go ahead and merge this one, since #825 should take care of documenting nodejs6 support

**Comment by rabbah** [comment]
In terms of the documentation, we're referring to `references.md` and the corresponding pr to bluemix-docs, yes? If that's going to be handled by #825 then let's either combine the two prs or wait until they're both ready so we don't have a inconsistency checked in.

**Comment by jasonpet** [comment]
@csantanapr - the docs (references.md) for the node.js 6 list of npm packages list is done and has been committed already.  However, you will need to update that list with these new ones you are adding.

**Comment by csantanapr** [comment]
Thanks @jasonpet for the heads up,  I will update the docs in this PR then.

**Comment by csantanapr** [comment]
please review

**Comment by csantanapr** [comment]
ppg 921

**Comment by rabbah** [comment]
Merged as https://github.com/openwhisk/openwhisk/commit/4a3d61e1e94bd6bb6da72bbca6db4849b770e3e5.

**Pull request closed without merging**
