### PR TITLE
Correct timeout doc

### PR DESCRIPTION
**Pull request by ind1go**
This timeout doesn't match the description at the moment.

### CODE REVIEW

**Comment by rabbah** [comment]
@csantana I recall changing this to 2s? In any case I think lower timeout is better for the tutorial.

**Comment by ind1go** [comment]
Cool, I can change both places down to 2000ms if we're happier with that.

(sorry for the close/open/close/... history of this pull request - Travis is not happy when there's a worldwide DNS DDOS attack!)

**Comment by rabbah** [comment]
Thanks - i think 2secs is enough.

**Comment by ind1go** [comment]
Reverted to use 2s in the code, and changed the doc to match.

**Comment by csantanapr** [comment]
@ind1go LGTM, thanks for the PR

**Pull request merged**
