### PR TITLE
Use Result URL Parameter when Invoking Actions

### PR DESCRIPTION
**Pull request by dubeejw**
- Instead of programmatically obtaining the result field from an activation record for action invocations, get the result from the backend by using the result=true URL parameter

Closes https://github.com/openwhisk/openwhisk/issues/1743

### CODE REVIEW

**Comment by dubeejw** [comment]
PG2 995

**Comment by dubeejw** [comment]
PG2 1000

**Comment by dubeejw** [comment]
PG approved.

**Comment by dubeejw** [comment]
@rabbah, please review.

**Comment by dubeejw** [comment]
@rabbah, as a side effect of this PR, it will be easier in the future to modify the action invocation to not encode the API response scheme with the CLI.

**Comment by rabbah** [comment]
> @rabbah, as a side effect of this PR, it will be easier in the future to modify the action invocation to not encode the API response scheme with the CLI.

woot woot!

**Comment by rabbah** [comment]
@dubeejw LG. Anything preventing the schema removal now?

**Comment by dubeejw** [comment]
@rabbah, was planning on removing the schema after this was merged.

**Pull request merged**
