### PR TITLE
Bump gradle to 3.3

### PR DESCRIPTION
**Pull request by markusthoemmes**
- Bump gradle version
- Remove deprecated use of the leftshift operator

### CODE REVIEW

**Comment by markusthoemmes** [comment]
Rebased on latest master.

**Comment by rabbah** [comment]
this is not assigned @markusthoemmes - tag someone.

**Comment by rabbah** [comment]
pg?

**Comment by rabbah** [comment]
Merged as https://github.com/openwhisk/openwhisk/commit/56d74c900d8694fd731b7778e000af5caca83935.

**Pull request closed without merging**
