### PR TITLE
Prevent Entity Names from being Modified

### PR DESCRIPTION
**Pull request by dubeejw**
- Display un-URL encoded entity names to the user

Fixes https://github.com/openwhisk/openwhisk/issues/1170

### CODE REVIEW

**Comment by dubeejw** [comment]
PG 278.

**Comment by dubeejw** [comment]
@mdeuser, this is ready for review as well.

**Comment by dubeejw** [comment]
@mdeuser, can you merge after your review, or assign to someone else to merge?

**Comment by csantanapr** [comment]
I guess review is done, and this PR is ready to be merge. going to remove the "review" label

**Comment by csantanapr** [comment]
rebase and merged 804aaecc0906bca30d00adced250277a75d0a576

**Pull request closed without merging**
