### PR TITLE
Update copyright-headers

### PR DESCRIPTION
**Pull request by cbickel**
This PR updates all copyright headers to 2017.

### CODE REVIEW

**Comment by rabbah** [comment]
should we check on dev@openwhisk.apache first on what the practice is (unless it's already documented somewhere)?

**Comment by mrutkows** [comment]
@rabbah @cbickel It would be good to ask th epolicy for Apache; I would assume you would leave the earliest (year) copyright "as is" and only update to 2017 as you go/add new function.

**Comment by csantanapr** [comment]
@rabbah @markusthoemmes Here is the Apache information on dealing with headers: https://www.apache.org/legal/src-headers.html

The net is there is standard header for Apache, and doesn't include dates.

The bigger question is do we need to change all our headers to Apache copyright, or just new files, or only for new files once graduated from Incubation.

I think is worth asking in the legal discuss mailing list.

**Comment by csantanapr** [comment]
As a side note, Apache provides an auditing tool [RAT](https://creadur.apache.org/rat/) that helps audit licenses, including parsing the headers.

**Comment by csantanapr** [comment]
FYI: We use RAT in cordova release automation tools https://github.com/apache/cordova-coho/blob/master/src/audit-license-headers.js

**Pull request closed without merging**
