### PR TITLE
Addition of bindTime:true for UI.

### PR DESCRIPTION
**Pull request by nwspeete-ibm**

### CODE REVIEW

**Comment by rabbah** [comment]
@starpit to review.

**Comment by starpit** [comment]
i think this looks good. the only issue i can think of: should apiKey be required: true? 

i guess it isn't required at the package level, rather it is required at the action level. i.e. to invoke an action in this package requires an apiKey. but we suggest (bindTime:true) that it be provided ahead of time.

is this a start at the operational semantics of these annotations?

**Comment by rabbah** [comment]
> is this a start at the operational semantics of these annotations?

not yet.

**Comment by rabbah** [comment]
> should apiKey be required: true? 

by the UI resolution algorithm bindtime supersedes required, does it not? I find these to be redundant and see a future where only one exists.

**Comment by starpit** [comment]
agreed, required is a second (and less rich) way of expressing "has default value". a fact that could more completely be provided by specifying that value.

**Comment by rabbah** [comment]
@starpit signed off.

Rebased and merged as https://github.com/openwhisk/openwhisk/commit/c09186352c9c93aef959b4925dc8172820be0615.

**Pull request closed without merging**
