### PR TITLE
Add `action update` test that expects failure when missing file is specified

### PR DESCRIPTION
**Pull request by mdeuser**
Add `action update` test that expects failure when missing file is specified

### CODE REVIEW

**Comment by mdeuser** [comment]
@dubeejw - Ready for review.

**Comment by mdeuser** [comment]
IPG 269

**Comment by mdeuser** [comment]
Fixes #565

**Comment by mdeuser** [comment]
IPG 'action update with missing file` test case results look good
```
     [exec]     Starting test Wsk Action CLI should reject action update when specified file is missing at 2016-07-07 20:28:16.514
     [exec] 
     [exec] bluemix.cli.BluemixWskBasicTests > Wsk Action CLI should reject action update when specified file is missing STANDARD_OUT
     [exec]     deleting updateMissingFile
     [exec] 
     [exec] bluemix.cli.BluemixWskBasicTests > Wsk Action CLI should reject action update when specified file is missing PASSED
```

**Comment by rabbah** [comment]
I'm not sure I understand this commit - It seems to reverse a previous commit: https://github.com/mdeuser/openwhisk/commit/5295f25514e455c1eaa492bce519b33f8b1a554d#diff-1a947144b344358c7bf829db2b035bdc?

**Comment by mdeuser** [comment]
The proposed Go error message when a nonexistent file name is provided is `errMsg := fmt.Sprintf("File '%s' is not a valid file or it does not exist: %s", artifact, err)`.  The `os.Stat()` is pretty much an existence test.  The existing `action create` test case is looking for 'not a valid file' in the "missing file" error message, so the Go CLI included that bit of text in that error message.  Here's the test case snippet.
```
    it should "reject create with missing file" in {
        wsk.action.create("missingFile", Some("notfound"),
            expectedExitCode = MISUSE_EXIT).
            stderr should include("not a valid file")
```

**Comment by rabbah** [comment]
Merged as https://github.com/openwhisk/openwhisk/commit/f31c0920a8c4535e4804212a1b0787d4a445097e.

**Pull request closed without merging**
