### PR TITLE
add Cloudant query utility to CouchDB Rest Client

### PR DESCRIPTION
**Pull request by sjfink**

### CODE REVIEW

**Comment by psuter** [comment]
Should we maybe add a safety check in `simpleQuery`? E.g.

```
if(!urlBase.toLowercase.contains("cloudant")) {
    warn(this, s"Warning: performing ad-hoc query on non-Cloudant host ('$urlBase').")
}
```

**Comment by rabbah** [comment]
Is it too much to put this in a `CloudantDbRestClient` which extends `CouchDbRestClient`?

**Comment by sjfink** [comment]
introduced CloudantRestClient as requested

**Comment by psuter** [comment]
Merged as 816760ce767e2aab4f8778389f3c44c2ff297315

**Pull request closed without merging**
