### PR TITLE
issue #208: couchdb should use cloudant initdb task only in openwhisk code structure

### PR DESCRIPTION
**Pull request by lehoanganh**
Signed-off-by: Dominik Jall <djall@de.ibm.com>

### CODE REVIEW

**Comment by lehoanganh** [comment]
@markusthoemmes: the path is still for now relative. For reuse purpose, an absolute path in openwhisk is better.

**Comment by domdom82** [comment]
@lehoanganh pls add issue # to this PR

**Comment by mrutkows** [comment]
Actually,  there is an argument not to reuse, in that each could be viewed as an optional plug-in.  If we indeed move to a framework design for datastores (and we can granularize the install/build process to take in parameters to declare the specific DB plug-in you want) then it would be good for each configuration/setup/init to be independent of one another.

**Comment by lehoanganh** [comment]
@mrutkows: cloudant is also based on couchdb. The initdb step (multiple rest calls against db) is exactly same in both case cloudant and couchdb, so that the initdb step of couch should reuse cloudant. Otherwise, we have in both places same code.

If we have another db, the initdb step for such another db should be different of course.

**Comment by mrutkows** [comment]
Yes, I know the are the same, or rather one "includes" the other.  Despite having the same lineage, from an external users point-of-view, they are still separate entities and should not be cross-dependent in any of their install/config files IMO.

**Comment by lehoanganh** [comment]
you're rite. In order to use couch, one doesn't have to import cloudant role. we have had also this though before. but for now, we still don't have a better idea. But we keep it in mind.

**Pull request merged**
