### PR TITLE
add node-jq to nodeJs base image

### PR DESCRIPTION
**Pull request by sjfink**
I would like to claim jq is generally useful for composition use cases and thus deserves to be included in the base image.

If included, I will also contribute a jq action for the utils package.

### CODE REVIEW

**Comment by rabbah** [comment]
need to also update `reference.md` to include new package.

**Comment by sjfink** [comment]
`reference.md` updated

**Comment by csantanapr** [comment]
@rabbah interesting find `npm install` is not returning `0` when there are errors.

Now I wonder what other packages are not installing properly
short version
```
root@c4b23144f8af:/nodejsAction# npm install node-jq@0.5.2
Err: Error: ./configure --disable-maintainer-mode --prefix=/nodejsAction/node_modules/node-jq/b982397e-7d9b-4c70-bc63-d5198922dcde --bindir=/nodejsAction/node_modules/node-jq/bin && make && make install
Command failed: ./configure --disable-maintainer-mode --prefix=/nodejsAction/node_modules/node-jq/b982397e-7d9b-4c70-bc63-d5198922dcde --bindir=/nodejsAction/node_modules/node-jq/bin
./configure: line 3012: printf: write error: Broken pipe
configure: error: in `/nodejsAction/node_modules/node-jq/191231d8-2147-4778-b3d0-51986881a7b0':
configure: error: no acceptable C compiler found in $PATH
See `config.log' for more details
root@c4b23144f8af:/nodejsAction# echo $?
0
```

If I can't trust return code Who do I trust? 😢 

```
root@c4b23144f8af:/nodejsAction# npm install node-jq@0.5.2

> node-jq@0.5.2 postinstall /nodejsAction/node_modules/node-jq
> npm run install-binary


> node-jq@0.5.2 install-binary /nodejsAction/node_modules/node-jq
> node scripts/install-binary.js

Err: Error: ./configure --disable-maintainer-mode --prefix=/nodejsAction/node_modules/node-jq/b982397e-7d9b-4c70-bc63-d5198922dcde --bindir=/nodejsAction/node_modules/node-jq/bin && make && make install
Command failed: ./configure --disable-maintainer-mode --prefix=/nodejsAction/node_modules/node-jq/b982397e-7d9b-4c70-bc63-d5198922dcde --bindir=/nodejsAction/node_modules/node-jq/bin
./configure: line 3012: printf: write error: Broken pipe
configure: error: in `/nodejsAction/node_modules/node-jq/191231d8-2147-4778-b3d0-51986881a7b0':
configure: error: no acceptable C compiler found in $PATH
See `config.log' for more details

nodejsAction@0.0.1 /nodejsAction
`-- node-jq@0.5.2
  +-- bin-build@2.2.0
  | +-- archive-type@3.2.0
  | | `-- file-type@3.9.0
  | +-- decompress@3.0.0
  | | +-- buffer-to-vinyl@1.1.0
  | | +-- decompress-tar@3.1.0
  | | | +-- is-tar@1.0.0
  | | | +-- object-assign@2.1.1
  | | | +-- strip-dirs@1.1.1
  | | | | +-- get-stdin@4.0.1
  | | | | +-- is-absolute@0.1.7
  | | | | | `-- is-relative@0.1.3
  | | | | +-- is-natural-number@2.1.1
  | | | | `-- sum-up@1.0.3
  | | | +-- tar-stream@1.5.2
  | | | | +-- bl@1.2.0
  | | | | `-- end-of-stream@1.4.0
  | | | +-- through2@0.6.5
  | | | | `-- readable-stream@1.0.34
  | | | |   +-- isarray@0.0.1
  | | | |   `-- string_decoder@0.10.31
  | | | `-- vinyl@0.4.6
  | | |   `-- clone@0.2.0
  | | +-- decompress-tarbz2@3.1.0
  | | | +-- is-bzip2@1.0.0
  | | | +-- seek-bzip@1.0.5
  | | | | `-- commander@2.8.1
  | | | |   `-- graceful-readlink@1.0.1
  | | | `-- vinyl@0.4.6
  | | |   `-- clone@0.2.0
  | | +-- decompress-targz@3.1.0
  | | | +-- is-gzip@1.0.0
  | | | `-- vinyl@0.4.6
  | | |   `-- clone@0.2.0
  | | +-- decompress-unzip@3.4.0
  | | | +-- is-zip@1.0.0
  | | | +-- stat-mode@0.2.2
  | | | +-- through2@2.0.3
  | | | `-- yauzl@2.8.0
  | | |   +-- buffer-crc32@0.2.13
  | | |   `-- fd-slicer@1.0.1
  | | |     `-- pend@1.2.0
  | | `-- vinyl-assign@1.2.1
  | |   `-- object-assign@4.1.1
  | +-- download@4.4.3
  | | +-- caw@1.2.0
  | | | +-- is-obj@1.0.1
  | | | `-- object-assign@3.0.0
  | | +-- concat-stream@1.6.0
  | | | +-- inherits@2.0.3
  | | | `-- typedarray@0.0.6
  | | +-- each-async@1.1.1
  | | | +-- onetime@1.1.0
  | | | `-- set-immediate-shim@1.0.1
  | | +-- filenamify@1.2.1
  | | | `-- filename-reserved-regex@1.0.0
  | | +-- got@5.7.1
  | | | +-- duplexer2@0.1.4
  | | | +-- node-status-codes@1.0.0
  | | | +-- object-assign@4.1.1
  | | | +-- parse-json@2.2.0
  | | | | `-- error-ex@1.3.1
  | | | |   `-- is-arrayish@0.2.1
  | | | +-- pinkie-promise@2.0.1
  | | | | `-- pinkie@2.0.4
  | | | +-- timed-out@3.1.3
  | | | `-- unzip-response@1.0.2
  | | +-- gulp-decompress@1.2.0
  | | | `-- gulp-util@3.0.8
  | | |   +-- array-differ@1.0.0
  | | |   +-- array-uniq@1.0.3
  | | |   +-- beeper@1.1.1
  | | |   +-- chalk@1.1.3
  | | |   | +-- ansi-styles@2.2.1
  | | |   | +-- has-ansi@2.0.0
  | | |   | | `-- ansi-regex@2.1.1
  | | |   | +-- strip-ansi@3.0.1
  | | |   | `-- supports-color@2.0.0
  | | |   +-- dateformat@2.0.0
  | | |   +-- fancy-log@1.3.0
  | | |   | `-- time-stamp@1.0.1
  | | |   +-- gulplog@1.0.0
  | | |   | `-- glogg@1.0.0
  | | |   +-- has-gulplog@0.1.0
  | | |   | `-- sparkles@1.0.0
  | | |   +-- lodash._reescape@3.0.0
  | | |   +-- lodash._reevaluate@3.0.0
  | | |   +-- lodash._reinterpolate@3.0.0
  | | |   +-- lodash.template@3.6.2
  | | |   | +-- lodash._basecopy@3.0.1
  | | |   | +-- lodash._basetostring@3.0.1
  | | |   | +-- lodash._basevalues@3.0.0
  | | |   | +-- lodash._isiterateecall@3.0.9
  | | |   | +-- lodash.escape@3.2.0
  | | |   | | `-- lodash._root@3.0.1
  | | |   | +-- lodash.keys@3.1.2
  | | |   | | +-- lodash._getnative@3.9.1
  | | |   | | +-- lodash.isarguments@3.1.0
  | | |   | | `-- lodash.isarray@3.0.4
  | | |   | +-- lodash.restparam@3.6.1
  | | |   | `-- lodash.templatesettings@3.1.1
  | | |   +-- minimist@1.2.0
  | | |   +-- multipipe@0.1.2
  | | |   | `-- duplexer2@0.0.2
  | | |   |   `-- readable-stream@1.1.14
  | | |   |     +-- isarray@0.0.1
  | | |   |     `-- string_decoder@0.10.31
  | | |   +-- object-assign@3.0.0
  | | |   +-- through2@2.0.3
  | | |   `-- vinyl@0.5.3
  | | +-- gulp-rename@1.2.2
  | | +-- is-url@1.2.2
  | | +-- object-assign@4.1.1
  | | +-- read-all-stream@3.1.0
  | | +-- readable-stream@2.2.9
  | | | +-- buffer-shims@1.0.0
  | | | +-- core-util-is@1.0.2
  | | | +-- isarray@1.0.0
  | | | +-- process-nextick-args@1.0.7
  | | | +-- string_decoder@1.0.0
  | | | `-- util-deprecate@1.0.2
  | | +-- stream-combiner2@1.1.1
  | | +-- vinyl@1.2.0
  | | | +-- clone@1.0.2
  | | | +-- clone-stats@0.0.1
  | | | `-- replace-ext@0.0.1
  | | +-- vinyl-fs@2.4.4
  | | | +-- duplexify@3.5.0
  | | | | +-- end-of-stream@1.0.0
  | | | | | `-- once@1.3.3
  | | | | `-- stream-shift@1.0.0
  | | | +-- glob-stream@5.3.5
  | | | | +-- extend@3.0.1
  | | | | +-- glob@5.0.15
  | | | | +-- glob-parent@3.1.0
  | | | | | +-- is-glob@3.1.0
  | | | | | | `-- is-extglob@2.1.1
  | | | | | `-- path-dirname@1.0.2
  | | | | +-- micromatch@2.3.11
  | | | | | +-- arr-diff@2.0.0
  | | | | | | `-- arr-flatten@1.0.3
  | | | | | +-- array-unique@0.2.1
  | | | | | +-- braces@1.8.5
  | | | | | | +-- expand-range@1.8.2
  | | | | | | | `-- fill-range@2.2.3
  | | | | | | |   +-- is-number@2.1.0
  | | | | | | |   +-- isobject@2.1.0
  | | | | | | |   +-- randomatic@1.1.6
  | | | | | | |   `-- repeat-string@1.6.1
  | | | | | | +-- preserve@0.2.0
  | | | | | | `-- repeat-element@1.1.2
  | | | | | +-- expand-brackets@0.1.5
  | | | | | | `-- is-posix-bracket@0.1.1
  | | | | | +-- extglob@0.3.2
  | | | | | | `-- is-extglob@1.0.0
  | | | | | +-- filename-regex@2.0.0
  | | | | | +-- is-extglob@1.0.0
  | | | | | +-- is-glob@2.0.1
  | | | | | +-- kind-of@3.2.0
  | | | | | | `-- is-buffer@1.1.5
  | | | | | +-- normalize-path@2.1.1
  | | | | | | `-- remove-trailing-separator@1.0.1
  | | | | | +-- object.omit@2.0.1
  | | | | | | +-- for-own@0.1.5
  | | | | | | | `-- for-in@1.0.2
  | | | | | | `-- is-extendable@0.1.1
  | | | | | +-- parse-glob@3.0.4
  | | | | | | +-- glob-base@0.3.0
  | | | | | | | +-- glob-parent@2.0.0
  | | | | | | | `-- is-glob@2.0.1
  | | | | | | |   `-- is-extglob@1.0.0
  | | | | | | +-- is-dotfile@1.0.2
  | | | | | | +-- is-extglob@1.0.0
  | | | | | | `-- is-glob@2.0.1
  | | | | | `-- regex-cache@0.4.3
  | | | | |   +-- is-equal-shallow@0.1.3
  | | | | |   `-- is-primitive@2.0.0
  | | | | +-- ordered-read-streams@0.3.0
  | | | | +-- to-absolute-glob@0.1.1
  | | | | | `-- extend-shallow@2.0.1
  | | | | `-- unique-stream@2.2.1
  | | | |   `-- json-stable-stringify@1.0.1
  | | | |     `-- jsonify@0.0.0
  | | | +-- gulp-sourcemaps@1.6.0
  | | | | +-- convert-source-map@1.5.0
  | | | | `-- through2@2.0.3
  | | | +-- is-valid-glob@0.3.0
  | | | +-- lazystream@1.0.0
  | | | +-- lodash.isequal@4.5.0
  | | | +-- merge-stream@1.0.1
  | | | +-- object-assign@4.1.1
  | | | +-- strip-bom@2.0.0
  | | | | `-- is-utf8@0.2.1
  | | | +-- strip-bom-stream@1.0.0
  | | | | `-- first-chunk-stream@1.0.0
  | | | +-- through2@2.0.3
  | | | +-- through2-filter@2.0.0
  | | | | +-- through2@2.0.3
  | | | | `-- xtend@4.0.1
  | | | `-- vali-date@1.0.0
  | | `-- ware@1.3.0
  | |   `-- wrap-fn@0.1.5
  | |     `-- co@3.1.0
  | +-- exec-series@1.0.3
  | | +-- async-each-series@1.1.0
  | | `-- object-assign@4.1.1
  | +-- rimraf@2.6.1
  | | `-- glob@7.1.1
  | |   +-- fs.realpath@1.0.0
  | |   +-- inflight@1.0.6
  | |   | `-- wrappy@1.0.2
  | |   +-- minimatch@3.0.3
  | |   | `-- brace-expansion@1.1.7
  | |   |   +-- balanced-match@0.4.2
  | |   |   `-- concat-map@0.0.1
  | |   +-- once@1.4.0
  | |   `-- path-is-absolute@1.0.1
  | +-- tempfile@1.1.1
  | | +-- os-tmpdir@1.0.2
  | | `-- uuid@2.0.3
  | `-- url-regex@3.2.0
  |   `-- ip-regex@1.0.3
  +-- download@5.0.3
  | +-- caw@2.0.0
  | | +-- get-proxy@1.1.0
  | | | `-- rc@1.2.1
  | | |   +-- deep-extend@0.4.1
  | | |   +-- ini@1.3.4
  | | |   `-- strip-json-comments@2.0.1
  | | `-- tunnel-agent@0.4.3
  | +-- decompress@4.1.0
  | | +-- decompress-tar@4.1.0
  | | +-- decompress-tarbz2@4.1.0
  | | | `-- unbzip2-stream@1.0.11
  | | |   +-- buffer@3.6.0
  | | |   | +-- base64-js@0.0.8
  | | |   | `-- ieee754@1.1.8
  | | |   `-- through@2.3.8
  | | +-- decompress-targz@4.0.0
  | | +-- decompress-unzip@4.0.1
  | | | `-- get-stream@2.3.1
  | | |   `-- object-assign@4.1.1
  | | +-- graceful-fs@4.1.11
  | | `-- strip-dirs@2.0.0
  | |   `-- is-natural-number@4.0.1
  | +-- filenamify@2.0.0
  | | +-- filename-reserved-regex@2.0.0
  | | +-- strip-outer@1.0.0
  | | | `-- escape-string-regexp@1.0.5
  | | `-- trim-repeated@1.0.0
  | +-- get-stream@3.0.0
  | +-- got@6.7.1
  | | +-- create-error-class@3.0.2
  | | | `-- capture-stack-trace@1.0.0
  | | +-- duplexer3@0.1.4
  | | +-- is-redirect@1.0.0
  | | +-- is-retry-allowed@1.1.0
  | | +-- is-stream@1.1.0
  | | +-- lowercase-keys@1.0.0
  | | +-- safe-buffer@5.0.1
  | | +-- timed-out@4.0.1
  | | +-- unzip-response@2.0.1
  | | `-- url-parse-lax@1.0.0
  | |   `-- prepend-http@1.0.4
  | +-- mkdirp@0.5.1
  | | `-- minimist@0.0.8
  | `-- pify@2.3.0
  +-- is-valid-path@0.1.1
  | `-- is-invalid-path@0.1.0
  |   `-- is-glob@2.0.1
  |     `-- is-extglob@1.0.0
  +-- strip-eof@1.0.0
  `-- tempfile@2.0.0
    +-- temp-dir@1.0.0
    `-- uuid@3.0.1

npm WARN nodejsAction@0.0.1 No description
npm WARN nodejsAction@0.0.1 No repository field.
npm WARN nodejsAction@0.0.1 No license field.
root@c4b23144f8af:/nodejsAction# echo $?
0
```

**Comment by sjfink** [comment]
yuck.   I'm going to withdraw this PR and look into using lodash instead.

**Comment by rabbah** [comment]
FWIW we do another open PR that would install g++ https://github.com/openwhisk/openwhisk/pull/1786/files.

**Comment by csantanapr** [comment]
I was thinking installing jq binary json apt-get and a modify version of node-jq but that also works

**Comment by csantanapr** [comment]
@rabbah I think  PR #1786 should be closed since we now have an action people can use to produce kafka messages using python. 
Installing `g++` and `make` to make `node-jq` would work we just need to see what's the size of the image increase (~50MB), or install `apt-get install -y jq` (~ 1 MB)

**Pull request closed without merging**
