### PR TITLE
Add trigger limits to docs and update docs for new docker skeleton.

### LINKED ISSUE #1025: Doc rate limits for action invocations and trigger fires
Document was already implemented here:     https://github.com/openwhisk/openwhisk/blob/master/core/controller/src/main/scala/whisk/core/entitlement/Entitlement.scala#L86

```
private val invokeRateThrottler = new RateThrottler(config, 120, 3600)
private val triggerRateThrottler = new RateThrottler(config, 60, 720)
```

### PR DESCRIPTION
**Pull request by rabbah**
Fixes #1025.

### CODE REVIEW

**Comment by csantanapr** [comment]
LGTM
go ahead and squash with final commit message(s) 😉

**Comment by rabbah** [comment]
done.

**Comment by csantanapr** [comment]
@rabbah 
The docs are correct, but there are problems with the sdk that was pushed
I opened two issues:
- #1129 
- #1130

**Comment by csantanapr** [comment]
rebase and merged 7f933a9d84a1741b0186049d8cb645cd42cbaade

**Pull request closed without merging**
