### PR TITLE
Bring the logMarkers to a consistent form #287

### PR DESCRIPTION
**Pull request by ChrBi**
As discussed this afternoon, I changed the markers to a consistent form.

### CODE REVIEW

**Comment by ioana-blue** [comment]
Looks ok. Do we have a blue playground for this?

**Comment by ChrBi** [comment]
@ioana-blue I'm not sure, if I have started one.
I will do a rebase and start a blue playground build afterwards.

**Comment by ioana-blue** [comment]
@rabbah assign this to me if you'd like me to merge this one.

**Comment by rabbah** [comment]
Yours. But wait for PG there was a regression.

**Comment by ChrBi** [comment]
The perf PG passed now.

**Comment by ioana-blue** [comment]
Still in paranoid mode, so need to wait a couple of days to merge this.

**Comment by ioana-blue** [comment]
Merged [here](https://github.com/openwhisk/openwhisk/commit/2492ffeddd24190122a61933827e02c4ce9b35bc)

**Pull request closed without merging**
