### PR TITLE
Remove unnecessary use of DocInfo on DB get where DocId is sufficient.

### PR DESCRIPTION
**Pull request by rabbah**
@starpit FYI.
pg2/201.

### CODE REVIEW

**Comment by starpit** [comment]
this looks good. on top of this, for #1260, we will need to excise the cacheKeys bits, confirm?

**Comment by rabbah** [comment]
yes - we don't need to cache both w/ and w/o rev. deferring that bit to your pr.

**Comment by starpit** [comment]
great, i'll merge this into my branch and clean up the cacheKeys cruft

**Comment by psuter** [comment]
Merged as e46c8aa701dc794ab1bd67fec70a2206fec14a6a

**Pull request closed without merging**
