### PR TITLE
Add Go CLI to OpenWhisk - Defect Fixes

### PR DESCRIPTION
**Pull request by dubeejw**
- Fix failing test cases
  - WebSocket test fixes
  - Package Insert name was being query escaped twice

### CODE REVIEW

**Comment by dubeejw** [comment]
@mdeuser, please review.

**Comment by mdeuser** [comment]
Review complete ready for merge
@csantanapr

**Comment by csantanapr** [comment]
What is a Defect? :trollface: 
We call those "bugs" or "issues" 😸

**Comment by csantanapr** [comment]
rebase and merged a205b65eacaf4c8b3036794da7611cadf8fffa01

**Pull request closed without merging**
