### PR TITLE
remove createImmortalDB 

### PR DESCRIPTION
**Pull request by ddragosd**
auth_index.json was committed with https://github.com/openwhisk/openwhisk/commit/a32766cbc545df8137f90c66c2ad3fdcfed3f348

### CODE REVIEW

**Comment by markusthoemmes** [comment]
Is this file even used by anything still?

**Comment by rabbah** [comment]
```
> grep -r createImmortalDBs.sh openwhisk
Binary file ./.git/index matches
```

seems not. @ddragosd do you use this for the compose bits?

**Comment by ddragosd** [comment]
@rabbah @markusthoemmes yes, I'm using this for `docker-compose`. Should we move it with the docker-compose scripts and remove it from this repo ?

**Comment by ddragosd** [comment]
@rabbah @markusthoemmes done. The automated build unfortunately times out in Travis as it exceeds the max time.

**Comment by rabbah** [comment]
Thanks @ddragosd - we should be able to merge this without issue but I've restarted travis anyway.

**Comment by rabbah** [comment]
Merged as https://github.com/openwhisk/openwhisk/commit/de2a829f5ec12e31f4663e957b7491c0fcac06f7.

**Pull request closed without merging**
