### PR TITLE
Update weather package to use username and password not apiKey.

### PR DESCRIPTION
**Pull request by nwspeete-ibm**

### CODE REVIEW

**Comment by nwspeete-ibm** [comment]
[Ready for merge] @starpit Please review and merge if all looks ok, thanks.

**Comment by rabbah** [comment]
pg?

**Comment by nwspeete-ibm** [comment]
http://whiskjenkins.sl.cloud9.ibm.com:8080/job/perfPlayground/900/

**Comment by jasonpet** [comment]
Don't forget to update the documentation (catalog.md)

**Comment by csantanapr** [comment]
rebase and merge 54b583cf2998592996cd8223bb4cb7f2d8d5c4e3

**Pull request closed without merging**
