### PR TITLE
Go CLI binary file compression

### PR DESCRIPTION
**Pull request by mdeuser**
Compress Go CLi binaries for faster downloads.  See #577

For all architectures:
Windows: wsk.exe -> wsk.exe.zip
Mac:     wsk     -> wsk.tar.gz
Linux:   wsk     -> wsk.tar.gz

### CODE REVIEW

**Comment by mdeuser** [comment]
@dubeejw - Would you kindly review the GO CLI build.xml changes.  Thanks!

**Comment by csantanapr** [comment]
@mdeuser can you rebase and squash into a single commit please?

**Comment by csantanapr** [comment]
LGTM to me I will wait for @dubeejw to signed off with a 👍

**Comment by dubeejw** [comment]
@mdeuser, you may want to sync up with Vincent as he is zipping the binaries when publishing them to nginx.

**Comment by dubeejw** [comment]
@houshengbo, are you compressing the binaries when publishing to nginx?

**Comment by dubeejw** [comment]
@mdeuser, @houshengbo, please refer to openwhisk/ansible/roles/cli/tasks/deploy.yml to see how Ansible compresses, and publishes the Python CLI. I'm not sure we want to support deploying the binaries with Ant as well.

**Comment by dubeejw** [comment]
@mdeuser, @houshengbo, with Ansible we can tar the binaries in the Docker container then publish the binaries to nginx.

**Comment by mdeuser** [comment]
@dubeejw - I did try to compress within Docker (no ansible), but the zip command was not available in the docker image, so I had to move the compression into the build scripts.

**Comment by dubeejw** [comment]
@mdeuser, I see now. It looks like the Python CLI is compressed during the Gradle build via the distTar task. I had to convert the Go CLI build from Ansible to Gradle as there were numerous issues trying to get Jenkins to build the CLI with Ansible. @csantanapr , the build.xml looks file. :+1:  We should include the compression routine in the new Gradle build script though.

**Comment by csantanapr** [comment]
Check @domdom82 with about Ansible problems, if doing with Gradle need to check how to do zip (for windows) in addition of tgz (mac, linux).

So let's not do it with ant, and just do it with final solution, let's not waist more effort on ant

**Comment by dubeejw** [comment]
@csantanapr, there are distTar, and distZip tasks. The distZip should cover the compressed binaries for Windows.

**Comment by dubeejw** [comment]
Using Gradle to build the CLI is nice because you can hotswap Gradle to just build the CLI: gradle :tools:go-cli:distDocker.

**Comment by csantanapr** [comment]
Great so let's do both using gradle then

**Comment by mdeuser** [comment]
@csantanapr - commits are squashed.

**Comment by csantanapr** [comment]
@mdeuser I should not merge this right? It's using ant instead of gradle

**Comment by mdeuser** [comment]
@dubeejw - After digging a bit into the python CLI build, it seems that the packaging of the CLI into the openwhisk-0.1.0.tar.gz file is performed inside the Docker image, not in the CLI's docker.gradle file.  In comment https://github.com/openwhisk/openwhisk/pull/675#issuecomment-226575764 the packaging was thought to be performed by a gradle file, but I can't find that.  Can you confirm?  Thanks!

**Comment by csantanapr** [comment]
So it looks this is WIP

**Comment by mdeuser** [comment]
The Go CLI binary compression is now moved the Go CLI build scripts into the Go CLI Dockerfile.
The compressed file names are as follows.  The python CLI and Bluemix CLI downloads use the a product/feature label in the download file name (i.e. "openwhisk"); these file names now follow that convention:
Windows:
- `openwhisk-win-386.zip`
- `openwhisk-win-amd64.zip`

Mac: 
- `openwhisk-mac-386.tar.gz`
- `openwhisk-mac-amd64.tar.gz`
- `openwhisk-mac-arm.tar.gz`
- `openwhisk-mac-arm64.tar.gz`

Linux:
- `openwhisk-linux-386.tar.gz`
- `openwhisk-linux-amd64.tar.gz`
- `openwhisk-linux-arm.tar.gz`
- `openwhisk-linux-arm64.tar.gz`
- `openwhisk-linux-mips64.tar.gz`
- `openwhisk-linux-mips64le.tar.gz`
- `openwhisk-linux-ppc64.tar.gz`
- `openwhisk-linux-ppc64le.tar.gz`

**Comment by mdeuser** [comment]
@dubeejw - Ready for another review please.  Thanks!

/cc @csantanapr

**Comment by dubeejw** [comment]
@mdeuser, @csantanapr, looks good to me.

**Comment by csantanapr** [comment]
Merged with a7fb2b3ea30a2d1193050f2ff1c9c5089be39b7f

**Pull request closed without merging**
