### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by lzbj**
Add one build tip.

### CODE REVIEW

**Comment by markusthoemmes** [comment]
Thanks for the pull request, good catch.

There will be a huge overhaul of `docker.gradle` in #109. Once that is merged, the timeout is settable via `-PdockerTimeout=480` on the gradle command itself.

**Comment by lzbj** [comment]
thanks, that would be great.

**Comment by markusthoemmes** [comment]
Squashed your commits and did some rewording 821a8b4855dd2c6003622c662d6ceb14aad36b18. Thanks for your contribution @lzbj

**Comment by lzbj** [comment]
thank you markusthoemmes.

**Pull request closed without merging**
