### PR TITLE
Adding `requests` to the python container

### PR DESCRIPTION
**Pull request by markusthoemmes**
- Add the requests module to the python container
- Add tests to assert that module installation for the python container works as expected.

Solves #1190

### CODE REVIEW

**Comment by rabbah** [comment]
Any other packages we lost/should include?

**Comment by psuter** [comment]
Here's my personal list:

    pip install beautifulsoup
    pip install httplib2
    pip install lxml
    pip install python-dateutil
    pip install scrapy
    pip install simplejson
    pip install twisted

**Comment by rabbah** [comment]
@markusthoemmes added a simple test for `request`. I suggest we augment the test to require the installed packages but do not necessarily need to test each one of that.

**Comment by rabbah** [comment]
Added @psuter's list with some more tests here: https://github.com/openwhisk/openwhisk/commit/d2df2c2466786a58f1b9170f8cc2074f865ba7e3.

**Pull request closed without merging**
