### PR TITLE
remove docs for cloudant and alarm

### LINKED ISSUE #515: packages.md describes how to use Alarm package which does not exist in OpenWhisk
Please see issue [390](https://github.com/openwhisk/openwhisk/issues/390) as this might resolve the issue; however it has been backlogged for 14 days as of this authoring.

The file docs/[packages.md](https://github.com/openwhisk/openwhisk/blob/master/docs/packages.md) assumes that both **cloudant** and **alarms** packages are available (neither are).

Therefore the entire section titled:

**Creating and using trigger feeds**
All steps assume use of alarm trigger:
1. Get a description of the feed in the /whisk.system/alarms package.
   `$ wsk package get --summary /whisk.system/alarms`
2. Create a trigger that fires every eight seconds.
   `$ wsk trigger create everyEightSeconds --feed /whisk.system/alarms/alarm -p cron '*/8 * * * * *' -p trigger_payload '{"name":"Mork", "place":"Ork"}'`

and all subsequent steps will not work... (if it wasn't apparent from step 1. which shows a package list that does not include these missing packages).

### PR DESCRIPTION
**Pull request by csantanapr**
Fixes #515 #514 
We should not document these on this repo until the content is available in the public.

This documentation remains in the product docs in [github.com/IBM-Bluemix](https://github.com/IBM-Bluemix/docs/blob/master/openwhisk/openwhisk_catalog.md) the content will not be lost.

### CODE REVIEW

**Comment by bjustin-ibm** [comment]
@csantanapr I did a case-insensitive text search for "cloudant" in `open/**/*.md` and still found lots of references to the cloudant OW package. For example there are a bunch in `open/docs/packages.md`

**Comment by rabbah** [comment]
These packages will eventually be in openwhisk-catalog, so will the relevant docs move there?
If we remove the cloudant bits which show off how to use packages, we will need to replace them with new samples.

**Comment by csantanapr** [comment]
@rabbah IMHO I think we should make the `openwhisk-catalog` smaller not bigger.
I think we should create a `openwhisk-package-couchdb` repo and put the package content that allows users to use coucdb or cloudant with the package, and corresponding docs for that package live in the same repo.

Since this is not available yet, then I want to remove references to content that is not public yet.

**Comment by csantanapr** [comment]
>If we remove the cloudant bits which show off how to use packages, we will need to replace them with new samples.

What specific text or usage of packages you think we are loosing?
how to use packages is already covered in [docs/packages.md](https://github.com/openwhisk/openwhisk/blob/master/docs/packages.md)

**Comment by rabbah** [comment]
Do we have a feed example without alarm or cloudant? I'll audit the rest. Keep in mind when the other samples also move then more bits have to come out or be replaced.

**Comment by csantanapr** [comment]
@rabbah nevermind, I know what you mean know, `packages.md` uses cloudant 😵

**Comment by csantanapr** [comment]
Closing this PR, alarm and cloudant is spread everywhere. I will spent a lot of time re-writing the docs, I preferred to spend the time making open source package for alarm and couchdb/cloudant available and explaining with source code what an feed is.

**Pull request closed without merging**
