### PR TITLE
Add POST requests description to REST API doc

### PR DESCRIPTION
**Pull request by daisy-ycguo**
The current REST API in `docs/reference.md` lacks of POST requests.
Add POST request descriptions to the document.

### CODE REVIEW

**Comment by daisy-ycguo** [comment]
@csantanapr Please review.

**Comment by rabbah** [comment]
An example post to activate an action with parameters would be useful.

**Comment by rabbah** [comment]
@daisy-ycguo - while not part of the issue. do you think you can clarify `$BASEURL` which is used in the doc but not defined?

**Comment by csantanapr** [comment]
@rabbah I created an issue for your comment https://github.com/openwhisk/openwhisk/pull/527#issuecomment-222516972 on $BASEURL.

I think we can merge this PR as it's right now and discuss $BASEURL in the new issue

**Comment by csantanapr** [comment]
merged 969eb0ec2e8156f8b15f68c8b7f430f34b875f95

**Pull request closed without merging**
