### PR TITLE
change default timezone to UTC

### PR DESCRIPTION
**Pull request by sjfink**

### CODE REVIEW

**Comment by domdom82** [comment]
We should also get rid of all the `${docker.timezone.mount}` during deployment. Obsolete now.

Since I can't merge to master, assigning to @markusthoemmes

**Comment by sjfink** [comment]
@domdom82 regarding the process -- the 4 designated mergers (including me) are free to delegate merges to anyone.    My assigning a PR to you is my way of delegating a PR to you to merge.

Regarding docker.timezone.mount -- someone needs to set timezone in the containers.    Is this happening somewhere else?

**Comment by domdom82** [comment]
@sjfink the timezone in the ubuntu base image is Etc/UTC by default so we would not need to set it. Maybe on blackbox though.

**Comment by markusthoemmes** [comment]
rebased and merged ccdf5dd227216d642d93123a5c71bc1a3bd79403

**Pull request closed without merging**
