### PR TITLE
use docker port instead of docker inspect for action containers

### PR DESCRIPTION
**Pull request by csantanapr**
This will avoid the need for special networking route to private network on docker containers for local development on Mac.
With potential to allow the use of docker for mac.

### CODE REVIEW

**Comment by rabbah** [comment]
Note that per this issue https://github.com/openwhisk/openwhisk/issues/1334, the invoker will eschew calls to `docker inspect`.

**Comment by csantanapr** [comment]
@rabbah This PR is work in progress not ready.

I was already about replacing docker inspect for getting the info directly from config.json from under docker.

This PR is WIP, I wanted to investigate the option of having only for Mac Dev Environment  the ability of using `docker port`

This way we have a easier for people to setup their local dev environment, by avoiding the special network route tweak, and the ability to use docker for mac instead of docker-machine if they like

I was planning to make it conditional, if Mac then, if not then use the current mode.

But then I was curious if using `docker port` we don't hit the performance problems of using `inspect` 

That's why I'm debating if I should make condition in code with if Mac, or maybe control it thru wiskprops.

By doing with wiskprops property we than can control which method to use from the outside, and we can run the benchmark side by side more easier.

I think I would go in phases, solve one problem at a time and just solve it for Mac Dev, by detecting Mac.

**Comment by markusthoemmes** [comment]
Is the route tweak even necessary for plain deployment of OpenWhisk. I was under the impression its only needed for the actionContainer tests? Everything else is handled inside the VM anyway?

**Comment by csantanapr** [comment]
@markusthoemmes I think I know see what you mean.
Making myself more familiar with invoker, you are correct when the invoker executes docker commands does them from it's container using the docker cli from the invoker container out to the host where docker engine is located.
For the run and init also you are correct going from invoker container to action container they seat on the same subnet so goes thru internal network

But I think I found some tests that call run and init from docker host, when tests runs in addition of actionContainer tests.
Take a look at [tests/src/whisk/core/container/test/ContainerPoolTests.scala)](https://github.com/openwhisk/openwhisk/blob/master/tests/src/whisk/core/container/test/ContainerPoolTests.scala)

Is my assumption correct that when this tests run the run and init against the docker action happens from the machine running the test, not the invoker.

**Comment by rabbah** [comment]
You're right Carlos. These are the actionContainer tests that Markus alluded to.

**Comment by csantanapr** [comment]
what I don't get about this test is the use of localhost
@rr any ideas
https://github.com/openwhisk/openwhisk/blob/master/tests/src/whisk/core/container/test/ContainerPoolTests.scala#L62
```
    val config = new WhiskConfig(
        Map(selfDockerEndpoint -> "localhost",
            dockerEndpoint -> null,
            edgeHostName -> "localhost",
            invokerSerializeDockerOp -> "true",
            invokerSerializeDockerPull -> "true")
            ++ WhiskEntityStore.requiredProperties
            ++ WhiskAuthStore.requiredProperties)
```

**Comment by rabbah** [comment]
> was planning to make it conditional, if Mac then, if not then use the current mode.

This is dangerous in that we don't have Mac specific tests and makes the invoker platform aware where it isn't otherwise. A general solution is preferred.

**Comment by csantanapr** [comment]
@rabbah I think I understand now better. I agree from the invoker there is no need to do port mapping.

We already have a case where we detect Mac but only from test system 


For the test cases I was I aware of 1. actionContainers like @markusthoemmes commented
https://github.com/openwhisk/openwhisk/tree/master/tests/src/actionContainers

I also found 2. 
ContainerPoolTests.scala
https://github.com/openwhisk/openwhisk/blob/master/tests/src/whisk/core/container/test/ContainerPoolTests.scala#L62

Are there any other test that do docker run and then init/run on port 8080 with the internal ip from the test system?

**Comment by csantanapr** [comment]
revisiting this in a later time.

**Pull request closed without merging**
