### PR TITLE
calling ifttt maker channel from whisk

### PR DESCRIPTION
**Pull request by visahak**
Calling ifttt from whisk package Issue 117

### CODE REVIEW

**Comment by rabbah** [comment]
@starpit @vinodmut Do you want to suggest additional annotations?

**Comment by starpit** [comment]
requirement: sampleInput and sampleOutput annotations

highly desirable: field-level description fields

**Comment by visahak** [comment]
@starpit @vinodmut There is no particular sampleoutput that I want to show the user? should I just say -a sampleOutput '{}'

**Comment by vinodmut** [comment]
@visahak Yes, please `-a sampleOutput '{}'` is good. We do this now for `samples/hello.js`.

**Comment by csantanapr** [comment]
closing as abandoned PR

**Pull request closed without merging**
