### PR TITLE
Fix Travis build by explicit docker pull and pinning requests to 2.10.0

### PR DESCRIPTION
**Pull request by csantanapr**
running an experiment for Travis build

### CODE REVIEW

**Comment by csantanapr** [comment]
PG2 651

**Comment by csantanapr** [comment]
References:
https://github.com/docker/docker-py/pull/1324
https://github.com/ansible/ansible-modules-core/issues/5774

**Comment by csantanapr** [comment]
maybe we just need to update requests 2.10.0 and the docker pull for all docker images.
But from this issue https://github.com/docker/docker-py/issues/501 it looks like ansible docker_container doesn't pull specific tags if you already have an image with a different tag already pulled.

**Comment by jeremiaswerner** [comment]
@csantanapr good job! thank you!

**Pull request merged**
