### PR TITLE
[Ready] Place Go CLI binaries under a build/ folder to easily bulk copy all binaries for distribution

### PR DESCRIPTION
**Pull request by mdeuser**
Place Go CLI binaries under a bin/ folder to easily bulk copy all binaries for distribution

### CODE REVIEW

**Comment by mdeuser** [comment]
@dubeejw - Ready for review!

**Comment by dubeejw** [comment]
Seems like the binaries will still exist in the same folder structure the compressed files are in?

**Comment by mdeuser** [comment]
@dubeejw - yes, compressed and uncompressed in the same target folder for now

**Comment by mdeuser** [comment]
@dubeejw - recent commit to copy into openwhisk/bin/go-cli/ folder (with subfolders for platform and arch).  Review time again please :-)

**Comment by mdeuser** [comment]
Fixes #723 
Fixes #761

**Comment by dubeejw** [comment]
:+1: :+1:

**Comment by mdeuser** [comment]
@csantanapr - ready for merge now.  Multiple commits were squashed.  Thanks!

**Comment by csantanapr** [comment]
rebase and merged 558dbd8008d2d3beca38c44cef65b9203791a30e

**Pull request closed without merging**
