### PR TITLE
Posible undefined error for the node whisk.invoke

### PR DESCRIPTION
**Pull request by jasonpet**
Current code does not handle situation where result is undefined when it checks result.error

### CODE REVIEW

**Comment by jasonpet** [comment]
running pg3#52

**Comment by bjustin-ibm** [comment]
LGTM

FYI @rabbah

**Comment by rabbah** [comment]
whisk.[invoke|trigger] deprecated ;)

**Comment by rabbah** [comment]
Shall we close this and remove whisk.js entirely instead?

**Comment by jasonpet** [comment]
I assumed that was the plan since @bjustin-ibm never merged it.  I think we are waiting on @mdeuser to remove whisk object references from apigateway before removing whisk.js.

**Comment by mdeuser** [comment]
@jasonpet - the whisk object references are removed in PR #1730.. it's in review state now

**Pull request closed without merging**
