### PR TITLE
Fix CLI `api-experimental list` column alignment

### LINKED ISSUE #1646: 'wsk api-experimental list' : column headers not always aligned with column content
happens with long strings in the columns

### PR DESCRIPTION
**Pull request by mdeuser**
Fixes #1646

### CODE REVIEW

**Comment by mdeuser** [comment]
@csantanapr - PR is ready for submission/review process

**Comment by mdeuser** [comment]
PG3 173 - only failure was a swift test case.

**Comment by mdeuser** [comment]
@csantanapr rebased and squashed.  PG3 227

**Comment by csantanapr** [comment]
LGTM

**Comment by mdeuser** [comment]
PG3 229 - passed without any API GW failures

**Pull request merged**
