### PR TITLE
WIP: Hotfix for Swift 3 Docker build

### PR DESCRIPTION
**Pull request by psuter**

### CODE REVIEW

**Comment by csantanapr** [comment]
@psuter This will fix #600 ?

PG ?

**Comment by csantanapr** [comment]
It looks like this is a temp fix, let's leave #600 to track proper fix shows up in https://github.com/apple/swift-corelibs-libdispatch

**Comment by psuter** [comment]
@csantanapr that's the hope. PG 366.

**Comment by markusthoemmes** [comment]
Seems like this was fixed at the source?

**Comment by psuter** [comment]
Yes.

**Comment by csantanapr** [comment]
Any lessons learned for the future on this incident? Any actions to handle it better, notifications, prevent, etc..?

**Comment by psuter** [comment]
We should consider depending on fixed commits in their history, I think. Pulling from the latest is a recipe for disaster as we've seen when they break it, and also for surprises when a sterilized build jumps over many versions at once due to Docker caching.

On the downside, it's more work for us to port their improvements, which are still frequent at this early stage of development for Swift on Linux.

**Comment by csantanapr** [comment]
I agree then let's open an issue to discuss and move forward with what are the changes we need short term and long term.

**Comment by csantanapr** [comment]
@psuter 
Created #608 please add more input on what's your proposal to move forward. We can have folks like @jasonpet or @bjustin-ibm help if need it the work items.

**Pull request closed without merging**
