### PR TITLE
[ready] Relax the version for ansible to 2.* Fixes #530

### LINKED ISSUE #530: setup failing to install ansible using ubuntu-setup/ansible.sh
Affects vagrant and stand-alone ubuntu
```
Reading state information... Done
E: Version '2.0.2.0-1ppa~trusty' for 'ansible' was not found
sudo: pip: command not found
The program 'ansible' is currently not installed. To run 'ansible' please ask your administrator to install the package 'ansible'
The program 'ansible-playbook' is currently not installed. To run 'ansible-playbook' please ask your administrator to install the package 'ansible'
```

### PR DESCRIPTION
**Pull request by csantanapr**
Fixes #530

### CODE REVIEW

**Comment by csantanapr** [comment]
IPG 327

**Comment by rabbah** [comment]
@lehoanganh @domdom82

**Comment by domdom82** [comment]
the version needs to be at least 2.0.2.0. e.g. 2.0.1.0 will not work.

**Comment by domdom82** [comment]
I just saw that 2.1.0.0-1ppa~trusty is the latest (and now only) release.

So if we relax to 2.1.* it should be fine.

**Comment by domdom82** [comment]
@rabbah You can merge this. @csantanapr and I have discussed on #530 that 2.* hopefully never installs 2.0.1.0 again. I cannot merge into master myself.

**Comment by csantanapr** [comment]
@domdom82 for the review.
Running PG and local Vagrant build just to be sure, and then it will be ready to merge

**Comment by csantanapr** [comment]
IPG 328

**Comment by csantanapr** [comment]
@bjustin-ibm this is ready for merge. Already reviewed.

**Comment by jeremiaswerner** [comment]
@csantanapr @domdom82 when I run the command manually in vagrant I get. any idea?

```
vagrant@vagrant-ubuntu-trusty-64:~/openwhisk$ sudo apt-get install -y ansible=2.*
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Version '2.*' for 'ansible' was not found
```

**Comment by jeremiaswerner** [comment]
ignore my comment, I got it working by doing the preceding steps ;)

**Comment by bjustin-ibm** [comment]
Using #541 to resolve minor conflict.

**Comment by bjustin-ibm** [comment]
Merged with bc959d6cb2f760ec4d23e6bce0c64cc7716aa018

**Pull request closed without merging**
