### PR TITLE
Enable API GW routemgmt action tests

### PR DESCRIPTION
**Pull request by csantanapr**
PR on behave of @mdeuser for APIGW enablement of tests

### CODE REVIEW

**Comment by csantanapr** [comment]
PG2 763

**Comment by csantanapr** [comment]
PG2 764

**Comment by rabbah** [comment]
OK to merge this pr so that it will work with the meta-API handler since much of this package is already in. The routemgmt package will require further cleanup and refactoring as noted here https://github.com/openwhisk/openwhisk/issues/1511#issuecomment-266214580. Further consideration should be given to https://github.com/openwhisk/openwhisk/issues/1629.

**Comment by csantanapr** [comment]
merged 9c1b11dacbc2c7f95434e0f1aae4fbde29a36ec5

**Pull request merged**
