### PR TITLE
Issue 311 vagrant ui optional

### PR DESCRIPTION
**Pull request by domdom82**
"open" part of continuously testing vagrant image. should enable us to setup vagrant without GUI.

### CODE REVIEW

**Comment by csantanapr** [comment]
Hi @domdom82 I'm working on refactoring vagrant workflows.
Take a look at #360 I will take what you have here and incorporate into my work
With GUI I have it setup that ubuntu-desktop.sh is removed and gui is configured in Vagrantfile in addition of of vb.gui

**Comment by csantanapr** [comment]
Also @domdom82 I'm making GUI disable by default, it's easier and faster for end user.

**Comment by csantanapr** [comment]
Also by making GUI false by default, it's easier to put in Vagrant file and not need for `(/^(false|f|no|n|0)$/i)`

**Comment by domdom82** [comment]
@csantanapr ok fine with me. if @sjfink does not object, we can make GUI false by default.

**Comment by sjfink** [comment]
I have no objection.

**Comment by rabbah** [comment]
close as duplicate then?

**Comment by domdom82** [comment]
yes, sure.

**Pull request closed without merging**
