### PR TITLE
Additional logging for ActionContainer tests

### PR DESCRIPTION
**Pull request by markusthoemmes**
This is a stepping stone to be able to debug ActionContainer tests.

### CODE REVIEW

**Comment by paulcastro** [comment]
Supercedes #1727 ?

**Comment by rabbah** [comment]
that's an issue not a pr?

**Comment by rabbah** [comment]
is this intended to flush out the heisenbug in our jenkins or to merge?

**Comment by markusthoemmes** [comment]
Dont see harm in merging it @rr, do you?

**Pull request closed without merging**
