### PR TITLE
Add Apache licenses to Python files - Part 1

### PR DESCRIPTION
**Pull request by mrutkows**
Adding proper Apache license headers to all Python (.py) files.  

Doing this in stages, this PR being "part 1" to make sure this works and reviewers can get a general feeling for what we are doing and provide comment before doing the rest. 

Specifically, this PR updates the following files:
./openwhisk/core/actionProxy/actionproxy.py
./openwhisk/core/actionProxy/invoke.py
./openwhisk/core/pythonAction/cli/packagescripts/setup.py
./openwhisk/core/pythonAction/pythonrunner.py
./openwhisk/tools/build/checkLogs.py
./openwhisk/tools/build/scanCode.py
./openwhisk/tools/travis/box-upload.py

Subsequent PRs would then similarly address the remaining Python files. Specifically:

./openwhisk/ansible/callbacks/logformatter.py
./openwhisk/core/javaAction/init.py
./openwhisk/core/javaAction/run.py
./openwhisk/core/pythonAction/cli/packagescripts/__init__.py
./openwhisk/core/pythonAction/cli/wskaction.py
./openwhisk/core/pythonAction/cli/wskactivation.py
./openwhisk/core/pythonAction/cli/wskitem.py
./openwhisk/core/pythonAction/cli/wsknamespace.py
./openwhisk/core/pythonAction/cli/wskpackage.py
./openwhisk/core/pythonAction/cli/wskprop.py
./openwhisk/core/pythonAction/cli/wskrule.py
./openwhisk/core/pythonAction/cli/wsksdk.py
./openwhisk/core/pythonAction/cli/wsktrigger.py
./openwhisk/core/pythonAction/cli/wskutil.py
./openwhisk/core/swift3Action/buildandrecord.py
./openwhisk/core/swift3Action/swift3runner.py
./openwhisk/tests/dat/actions/hello.py
./openwhisk/tests/dat/actions/malformed.py
./openwhisk/tests/dat/actions/niam.py
./openwhisk/tests/dat/actions/stdenv.py
./openwhisk/tests/dat/actions/timedout.py
./openwhisk/tests/dat/actions/unicode.py
./openwhisk/tests/dat/blackbox/badaction/runner.py
./openwhisk/tools/admin/wskprop.py
./openwhisk/tools/admin/wskutil.py
./openwhisk/tools/db/replicateDbs.py
./openwhisk/tools/health/monitorUtil.py
./openwhisk/tools/json/validate.py

### CODE REVIEW

**Comment by rabbah** [comment]
@mrutkows please take this opportunity and delete `pythonAction/cli`? (These files are redundant with the openwhisk-python-cli repo.)

@csantanapr FYI.

**Comment by csantanapr** [comment]
Yes 💣  `pythonAction/cli`

**Comment by mrutkows** [comment]
So delete all files in the pythonAction/cli subdir...

**Comment by mrutkows** [comment]
Deleted the CLI directory as requested.  If this PR is acceptable, please merge; I have "part 2" saved locally and would like to submit those on a separate PR.

**Comment by rabbah** [comment]
Generally ok with this - shouldn't the license come first (top of the file) vs after some comments?
Are you intending for scanCode to work with these scripts?

**Comment by csantanapr** [comment]
scanCode should work this scripts, I think that's @markusthoemmes intention in his next PR.
merging this for now, and looking forward to learn some more about python and parsing the header @markusthoemmes 

Going to mer this for now.

**Comment by csantanapr** [comment]
going to run a PG

**Comment by rabbah** [comment]
> I think that's @markusthoemmes intention in his next PR.

really?

**Comment by csantanapr** [comment]
PG3 360

**Comment by csantanapr** [comment]
merged ff8a88f97e4443e7d0f1853e5517acb17a2848ce

**Comment by csantanapr** [comment]
>really? Did you mean @mrutkows?

What are you talking about? Your are imaging things 😸

**Pull request closed without merging**
