### PR TITLE
Fix API GW CLI swagger config file support

### PR DESCRIPTION
**Pull request by mdeuser**
The following error was observed when creating APIs with a swagger configuration file

```
error: Unable to create API: API route creation failure: {"error":"API configuration failure: {\"message\":\"Cannot read property 'indexOf' of undefined\"....
```

This PR fixes that failure.

### CODE REVIEW

**Comment by mdeuser** [comment]
PG3 86

**Comment by mdeuser** [comment]
@nwspeete-ibm FYI

**Comment by mdeuser** [comment]
@csantanapr - swagger test now added to the end-to-end health check

**Comment by mdeuser** [comment]
PG3 93 - failures in other tests

**Comment by csantanapr** [comment]
squashed and merged a1a40d18ff4f82faa60f11903d398555ac4befe9

**Pull request closed without merging**
