### PR TITLE
Fix incorrect new lines in tracing and stdout messages

### PR DESCRIPTION
**Pull request by mdeuser**
Fix incorrect new lines in tracing and stdout messages
- From comment https://github.com/openwhisk/openwhisk/pull/604#issuecomment-224987914

### CODE REVIEW

**Comment by mdeuser** [comment]
@dubeejw - Should be a quick review.
/cc @csantanapr

**Comment by csantanapr** [comment]
@mdeuser please next time assigned a reviewer using github when it's ready for review.
image

@dubeejw re-assign to me when it's ready for merge if you want to delegate merger.

**Comment by dubeejw** [comment]
@csantanapr, :+1: :+1:

**Comment by csantanapr** [comment]
rebase and merged 62779e4e587b1876aa27ac8ba0d0a19b484079cd

**Pull request closed without merging**
