### PR TITLE
Support for Java Actions

### PR DESCRIPTION
**Pull request by psuter**
Including tests. Works with the caveat that the action JAR must be "small" (for now). Superseeds #77.

### CODE REVIEW

**Comment by psuter** [comment]
TravisCI failure due to ConsulKV (see #79). Relaunched.

**Comment by psuter** [comment]
perf pg 119

**Comment by psuter** [comment]
...and regular pg 142!

**Comment by rabbah** [comment]
rebased and merged.

**Comment by psuter** [comment]
11556af73e96c7070173f1191ae1b27c82080b72

**Pull request closed without merging**
