### PR TITLE
Updated installWeather.sh sample text

### PR DESCRIPTION
**Pull request by nwspeete-ibm**

### CODE REVIEW

**Comment by csantanapr** [comment]
@nwspeete-ibm We are in dual maintenance mode, please submit PR to update `openwhisk-catalog` also:
https://github.com/openwhisk/openwhisk-catalog/blob/master/packages/installWeather.sh#L24

**Comment by csantanapr** [comment]
@nwspeete-ibm  PG?

**Comment by nwspeete-ibm** [comment]
PG #986

**Comment by nwspeete-ibm** [comment]
@csantanapr  [READY]

**Comment by nwspeete-ibm** [comment]
https://openwhisk-jenkins.swg-devops.com:8443/job/Playground1/155/

**Comment by nwspeete-ibm** [comment]
@csantanapr [READY] for merge. Playground build : Playground1 # 155

**Pull request merged**
