### PR TITLE
[Review] Go CLI Does Not Create Action with Empty File

### PR DESCRIPTION
**Pull request by dubeejw**
- Ensure code property always exists even if it is an empty string
- Add test case to ensure actions can be create with empty files
- Add test case to invoke an empty action

### CODE REVIEW

**Comment by dubeejw** [comment]
@mdeuser, ready for review.

**Comment by dubeejw** [comment]
IPG 227.

**Comment by dubeejw** [comment]
Please review.

**Comment by mdeuser** [comment]
@rabbah - What is the expected behavior when an action with no code is invoked?  Just wondering if that should also be part of this test.

**Comment by rabbah** [comment]
there should be a test for invoking a malformed action (an empty action is considered malformed).

**Comment by dubeejw** [comment]
Test added for invoking an empty action.

**Comment by dubeejw** [comment]
IPG 237.

**Comment by rabbah** [comment]
Rebased and merged as https://github.com/openwhisk/openwhisk/commit/51817283c204c055456646c8bfb536ab78d2fdf1.

**Pull request closed without merging**
