### PR TITLE
more cleaning up of Exec

### PR DESCRIPTION
**Pull request by rabbah**
Move the exec helpers to the test suite where they are used.
Remove subtypes (staging for complete removal of type disctinctions of runtimes).
Refactoring of the container image name construction to its own singleton (away from `WhiskAction`).

### CODE REVIEW

**Comment by rabbah** [comment]
pg3/338 🔵

**Comment by rabbah** [comment]
Rebased/Will re-pg.

**Comment by rabbah** [comment]
pg2/1​15​4 🔵.

**Comment by rabbah** [comment]
Rebased to master again.

**Comment by perryibm** [comment]
squashed/merged

**Pull request closed without merging**
