### PR TITLE
Fix Python CLI distTar Task

### LINKED ISSUE #801: gradle distDocker: docker cp cli:/cli/dist/ "/home/travis/build/openwhisk/openwhisk/tools/cli/build/distributions/"' failed with exitCode 1
Even the build succeeded, each time to run "gradle distDocker", we will get the following error:
```
Successfully built 8ff513a5c6cd

:tools:cli:removeDistribution UP-TO-DATE

:tools:cli:distTar

Executing 'docker rm -f cli'

Executing 'docker run --name cli whisk/cli'

Executing 'docker cp cli:/cli/dist/ "/home/travis/build/openwhisk/openwhisk/tools/cli/build/distributions/"'

Command 'docker cp cli:/cli/dist/ "/home/travis/build/openwhisk/openwhisk/tools/cli/build/distributions/"' failed with exitCode 1

Executing 'docker rm -f cli'

:tools:cli:tagImage

Executing 'docker tag -f whisk/cli whisk/cli:latest'

:tools:cli:pushImage SKIPPED

:tools:go-cli:distDocker
```

This is not some blocking issue, but we need to find out the cause and fix it.

### PR DESCRIPTION
**Pull request by dubeejw**
- Fix error that occurs during the gradle distTar task for the Python CLI

Fixes #801

### CODE REVIEW

**Comment by markusthoemmes** [comment]
Which failure is this supposed to fix? The quotes are there in case of spaces in paths.

**Comment by dubeejw** [comment]
@markusthoemmes 

```Executing 'docker cp cli:/cli/dist/ "/home/travis/build/openwhisk/openwhisk/tools/cli/build/distributions/"'

Command 'docker cp cli:/cli/dist/ "/home/travis/build/openwhisk/openwhisk/tools/cli/build/distributions/"' failed with exitCode 1```

**Comment by dubeejw** [comment]
@markusthoemmes, I've updated the commit. The Gradle exec() method expects an array of arguments instead of a string containing all of the arguments. With the array of arguments spaces are preserved in the directory path.

**Comment by markusthoemmes** [comment]
Would you check if the error is also present in #1023? I changed the way the python CLI's `run`.

**Comment by dubeejw** [comment]
Looks like the issue is fixed by your PR. However, you have to update the run commands if you want the status output to be displayed correctly.

**Comment by markusthoemmes** [comment]
As noted, fixed in #1023 which is now merged. Thanks for the hint with the `run` function, incooperated there.

**Pull request closed without merging**
