### PR TITLE
Add -g gradle flag allowing choosing explicit targets.

### PR DESCRIPTION
**Pull request by perryibm**
Add --testFilter flag to limit tests that are run.

### CODE REVIEW

**Comment by rabbah** [comment]
proposing to squash the following patch: https://github.com/openwhisk/openwhisk/commit/a1508cd7511021d31cb9ac6ed72d9380e4861e99

**Comment by rabbah** [comment]
we should add an example to the readme on how to use at least with -g to filter tests.

**Comment by perryibm** [comment]
ok - mods are good with me

**Comment by rabbah** [comment]
Mods squashed and merged as https://github.com/openwhisk/openwhisk/commit/e46d49dd890c59302216c94f6a19df95fd7893f0.

**Pull request closed without merging**
