### PR TITLE
Refactor overload and throttle checks to allow for overrides.

### PR DESCRIPTION
**Pull request by rabbah**
Refactor overload checks to allow for overrides.

### CODE REVIEW

**Comment by rabbah** [comment]
Playground build 30.

**Comment by sjfink** [comment]
@rabbah rebase your branch?

**Comment by sjfink** [comment]
@rabbah rebase your branch?

**Comment by sjfink** [comment]
also playground 31 failed many tests?

**Comment by perryibm** [comment]
Waiting for 32 now.  Is it a feature that Steve's comments/replies are in email only but not in the issue tracker?  (This is by email)
 
----- Original message -----From: Stephen Fink <notifications@github.com>To: openwhisk/openwhisk <openwhisk@noreply.github.com>Cc: Perry S Cheng/Cambridge/IBM@IBMUSSubject: Re: [openwhisk] Refactor overload and throttle checks to allow for overrides. (#40)Date: Wed, Mar 2, 2016 5:30 PM 
also playground 31 failed many tests?

**Comment by perryibm** [comment]
Can you explain how the override is activated?  Do you mean just code cleanup for method override or user-specific limits?

**Comment by rabbah** [comment]
Thanks. Override as in method override to facilitate an admin API to set rates per subject. As for the missing comments, that's my fault with slow page refresh I deleted them.

**Pull request merged**
