### PR TITLE
WIP: Allow Swift actions to optionally be declared inside a struct

### PR DESCRIPTION
**Pull request by bjustin-ibm**
OpenWhisk actions are expected to declare a global "main" function. However, this does not work well if you want to develop multiple actions in a single Xcode target, as you cannot re-declare a global main function.

This solution suggests that users working in Xcode may optionally declare their main function inside a struct, in order to solve the namespacing issue at compliation time. Just before the .swift code is run, if a struct declaration is found, peel away the struct to reveal the main function contained inside.

### CODE REVIEW

**Comment by paulcastro** [comment]
Is the intent to develop and run several actions in the same project?

I wonder if we could create an emulator using your proposed format.  It may also be possible to use closures. We can have a single main function that looks like main(params:[String:Any], actionCode: ([String:Any]) -> [String:Any]) -> [String: Any] { .. some code }.  Then the "main" function just takes parameters and closures and executes the closure.

**Comment by bjustin-ibm** [comment]
> Is the intent to develop and run several actions in the same project?

Yes, but I was more concerned with developing them - at least to the point of having them compile happily. I'm not so much concerned about running them, but... with the struct envelope, they can be run (say, in XCTest unit tests) as:

```
let response = SomeWhiskAction().main(["param": "value"])

// TODO assert stuff about the response
```

Obviously, that gets a little trickier if the action itself needs the OpenWhisk runtime in order to execute.

I did try using closures instead of named functions, but Swift limits what you are allowed to do outside of classes or structs. One of these limitations is that you can't declare an unnamed closure. These limits are lifted if your code is in a file called `main.swift`. But then you would have to write all your actions in that same `main.swift` file, which defeats the purpose as I cannot use the `wsk` CLI to create a single action from a file that defines multiple actions.

**Comment by rabbah** [comment]
Java actions require naming the main function. We've received feedback that for other runtimes, it is also desirable to do this. Would it solve the Swift/Xcode problem too if action entries can be named explicitly?

**Comment by bjustin-ibm** [comment]
> Would it solve the Swift/Xcode problem too if action entries can be named explicitly?

@rabbah It would help if we allow them to name the function whatever they want, and not require the function to be called `main`. In that way, having multiple actions in the same Xcode target wouldn't look to the compiler like they were trying to redefine a global function.

Perhaps another option is to have a backend/runtime object that allows the action developer to specify what they want to run as their action. Something that might look like:

```swift
// tell OpenWhisk that my action's implementation consists 
// of the code inside the supplied closure
Whisk.declareAction { parameters in 
    // my action implementation goes here
}
```

Now that I've written that all out... this seems quite a bit nicer than the struct envelope that requires peeling away before running the action.

**Comment by paulcastro** [comment]
Discussed this with @bjustin-ibm , it should be possible to provide an action authoring dev workflow that feels more natural to the developer, then create a pipeline to convert and load into OpenWhisk.  We can create a new issue around this and close this PR?

**Pull request closed without merging**
