### PR TITLE
speech to text action

### PR DESCRIPTION
**Pull request by joachimvaldez**
@jasonpet

### CODE REVIEW

**Comment by starpit** [comment]
the main thing that i think is missing here is the link between the `content_type` and `encoding` and `payload` fields. the former two define the interpretation of the latter, and yet this relation is not explicit in the metadata.

it'd be nice if the there were siblings in the input, e.g.

```
{ { payload: xxx, encoding: "base64", content_type: "audio/wav" }, ... }
```

but i realize that our annotations do not yet support specifications beyond the top level of nesting.

perhaps this is an issue better solved with a custom Instantiation page, but... i don't think i could take the annotations as they exist and automatically generate, i.e. by interpreting the annotations, a invoke/instantiate/bind UI that would let the user invoke this action.

**Comment by starpit** [comment]
it also just occurred to me that the need to encode the binary (speech) payload... it'd be nice to avoid this, but doing so may require backend support that doesn't exist? i'm not sure how whisk can pass through unencoded binary data to nodejs without some sort of special support.

because, as far as my (quite possibly flawed) understanding goes: nodejs, the only way to have this kind of data is to keep it off-heap (that's what the Buffer abstraction gives you)

**Comment by csantanapr** [comment]
I think this is ready for review/merge, @joachimvaldez can you rebase this PR, Github is reporting tht is out-of-date

**Comment by rabbah** [comment]
In general, most times the person doing the merge can rebase and ff without resolving conflicts. This avoids the added overhead of constantly rebasing.

**Comment by rabbah** [comment]
Rebased and merged as part of this [commit](https://github.com/openwhisk/openwhisk/compare/7a5e1240c0ac...f9b4f4841543).

**Pull request closed without merging**
