### PR TITLE
Update to golang 1.7 and CLI README fixes

### LINKED ISSUE #1352: Update to golang 1.7 (or at least 1.6.4 if it is ever released) -- wsk CLI crashing after updating to Sierra
Really not sure why but about every 10th call I blow up. I might try to rebuild the CLI with the absolute latest Go runtime to see if that somehow helps..

Here the stack trace I'm getting ...

$ wsk action invoke log -b -p hi there
fatal error: unexpected signal during runtime execution
[signal 0xb code=0x1 addr=0xb01dfacedebac1e pc=0x100ab]

runtime stack:
runtime.throw(0x653400, 0x2a)
	/usr/local/go/src/runtime/panic.go:547 +0x90
runtime.sigpanic()
	/usr/local/go/src/runtime/sigpanic_unix.go:12 +0x5a
runtime.unlock(0x8460a0)
	/usr/local/go/src/runtime/lock_sema.go:107 +0x14b
runtime.(*mheap).alloc_m(0x8460a0, 0x1, 0x10000000006, 0xb2ce38)
	/usr/local/go/src/runtime/mheap.go:492 +0x314
runtime.(*mheap).alloc.func1()
	/usr/local/go/src/runtime/mheap.go:502 +0x41
runtime.systemstack(0xc82003be58)
	/usr/local/go/src/runtime/asm_amd64.s:307 +0xab
runtime.(*mheap).alloc(0x8460a0, 0x1, 0x10000000006, 0xfd4f)
	/usr/local/go/src/runtime/mheap.go:503 +0x63
runtime.(*mcentral).grow(0x847610, 0x0)
	/usr/local/go/src/runtime/mcentral.go:209 +0x93
runtime.(*mcentral).cacheSpan(0x847610, 0xb2ce38)
	/usr/local/go/src/runtime/mcentral.go:89 +0x47d
runtime.(*mcache).refill(0x8f44b0, 0xc800000006, 0xb2ce38)
	/usr/local/go/src/runtime/mcache.go:119 +0xcc
runtime.mallocgc.func2()
	/usr/local/go/src/runtime/malloc.go:642 +0x2b
runtime.systemstack(0xc820018000)
	/usr/local/go/src/runtime/asm_amd64.s:291 +0x79
runtime.mstart()
	/usr/local/go/src/runtime/proc.go:1051

goroutine 188 [running]:
runtime.systemstack_switch()
	/usr/local/go/src/runtime/asm_amd64.s:245 fp=0xc820376988 sp=0xc820376980
runtime.mallocgc(0x50, 0x454b60, 0x1, 0xc8202e6630)
	/usr/local/go/src/runtime/malloc.go:643 +0x869 fp=0xc820376a60 sp=0xc820376988
runtime.newarray(0x454b60, 0x9, 0x37722d)
	/usr/local/go/src/runtime/malloc.go:798 +0xc9 fp=0xc820376aa0 sp=0xc820376a60
runtime.makeslice(0x5a5ee0, 0x9, 0x9, 0x0, 0x0, 0x0)
	/usr/local/go/src/runtime/slice.go:32 +0x165 fp=0xc820376af0 sp=0xc820376aa0
math/big.nat.divLarge(0x0, 0x0, 0x0, 0xc8202e6630, 0x12, 0x16, 0xc8202e6580, 0x11, 0x16, 0xc820397900, ...)
	/usr/local/go/src/math/big/nat.go:571 +0x4d6 fp=0xc820376ca0 sp=0xc820376af0
math/big.nat.div(0x0, 0x0, 0x0, 0xc8202e6580, 0x11, 0x16, 0xc8202e6580, 0x11, 0x16, 0xc820397900, ...)
	/usr/local/go/src/math/big/nat.go:538 +0x2f5 fp=0xc820376d48 sp=0xc820376ca0
math/big.(*Int).QuoRem(0xc820376e78, 0xc820376f80, 0xc8203a60c0, 0xc820376f80, 0xc8202d4420, 0x36ff2d)
	/usr/local/go/src/math/big/int.go:227 +0xe6 fp=0xc820376e10 sp=0xc820376d48
math/big.(*Int).Mod(0xc820376f80, 0xc820376f80, 0xc8203a60c0, 0xc820376f80)
	/usr/local/go/src/math/big/int.go:258 +0x13a fp=0xc820376ec0 sp=0xc820376e10
crypto/elliptic.(*CurveParams).doubleJacobian(0xc820117f00, 0xc8202d4400, 0xc8202d4420, 0xc8202d4440, 0xc8202d43c0, 0xc8202d43a0, 0xc8202d43e0)
	/usr/local/go/src/crypto/elliptic/elliptic.go:196 +0x8b fp=0xc820376fa8 sp=0xc820376ec0
crypto/elliptic.(*CurveParams).ScalarMult(0xc820117f00, 0xc8203a6180, 0xc8203a61c0, 0xc8200cad20, 0x42, 0x42, 0xa, 0xffffffffffffffff)
	/usr/local/go/src/crypto/elliptic/elliptic.go:257 +0x176 fp=0xc8203770c8 sp=0xc820376fa8
crypto/elliptic.(*CurveParams).ScalarBaseMult(0xc820117f00, 0xc8200cad20, 0x42, 0x42, 0xc820377160, 0x42)
	/usr/local/go/src/crypto/elliptic/elliptic.go:269 +0x51 fp=0xc820377110 sp=0xc8203770c8
crypto/elliptic.GenerateKey(0xb24158, 0xc820117f00, 0x9482a8, 0xc820016d20, 0xc8200cad20, 0x42, 0x42, 0x0, 0x0, 0x0, ...)
	/usr/local/go/src/crypto/elliptic/elliptic.go:299 +0x2b4 fp=0xc820377188 sp=0xc820377110
crypto/tls.(*ecdheKeyAgreement).generateClientKeyExchange(0xc820447980, 0xc82000c780, 0xc82000c8c0, 0xc82008f200, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/key_agreement.go:388 +0x1ef fp=0xc820377318 sp=0xc820377188
crypto/tls.(*clientHandshakeState).doFullHandshake(0xc820377e38, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/handshake_client.go:431 +0x121b fp=0xc8203779d0 sp=0xc820377318
crypto/tls.(*Conn).clientHandshake(0xc820234000, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/handshake_client.go:213 +0x1737 fp=0xc820377ee8 sp=0xc8203779d0
crypto/tls.(*Conn).Handshake(0xc820234000, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:1033 +0xec fp=0xc820377f28 sp=0xc820377ee8
net/http.(*Transport).dialConn.func3(0xc820234000, 0xc82020e480, 0xc820202e40)
	/usr/local/go/src/net/http/transport.go:831 +0x21 fp=0xc820377f68 sp=0xc820377f28
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1998 +0x1 fp=0xc820377f70 sp=0xc820377f68
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:836 +0x986

goroutine 1 [select]:
net/http.(*Transport).getConn(0xc8200c6000, 0xc8201a9b20, 0x0, 0xc820051a40, 0x5, 0xc8201debe0, 0x1c, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/http/transport.go:714 +0x4ef
net/http.(*Transport).RoundTrip(0xc8200c6000, 0xc8201a9b20, 0xc8200c6000, 0x0, 0x0)
	/usr/local/go/src/net/http/transport.go:314 +0x7e9
net/http.send(0xc8201a9b20, 0x948560, 0xc8200c6000, 0x0, 0x0, 0x0, 0xc820051b90, 0x0, 0x0)
	/usr/local/go/src/net/http/client.go:260 +0x6b7
net/http.(*Client).send(0x8407e0, 0xc8201a9b20, 0x0, 0x0, 0x0, 0x5b9cc0, 0x0, 0x0)
	/usr/local/go/src/net/http/client.go:155 +0x185
net/http.(*Client).doFollowingRedirects(0x8407e0, 0xc8201a9b20, 0x6a07a0, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/http/client.go:475 +0x8a4
net/http.(*Client).Do(0x8407e0, 0xc8201a9b20, 0xc820051960, 0x0, 0x0)
	/usr/local/go/src/net/http/client.go:191 +0x1e4
_/src/github.com/go-whisk/whisk.(*Client).Do(0xc820202900, 0xc8201a9b20, 0x428ca0, 0xc82002c450, 0x0, 0x0, 0x0)
	/src/github.com/go-whisk/whisk/client.go:214 +0x6c2
_/src/github.com/go-whisk/whisk.(*ActionService).Invoke(0xc82002c418, 0xc8201fd227, 0x3, 0xc8201deac0, 0xc8201dea01, 0x0, 0x0, 0x0, 0x0)
	/src/github.com/go-whisk/whisk/action.go:259 +0xacc
_/src/github.com/go-whisk-cli/commands.glob.func3(0x8380c0, 0xc8201dea00, 0x1, 0x2, 0x0, 0x0)
	/src/github.com/go-whisk-cli/commands/action.go:182 +0x11ad
github.com/spf13/cobra.(*Command).execute(0x8380c0, 0xc8201de880, 0x2, 0x2, 0x0, 0x0)
	/src/github.com/spf13/cobra/command.go:568 +0x668
github.com/spf13/cobra.(*Command).ExecuteC(0x83cd40, 0x8380c0, 0x0, 0x0)
	/src/github.com/spf13/cobra/command.go:658 +0x55c
github.com/spf13/cobra.(*Command).Execute(0x83cd40, 0x0, 0x0)
	/src/github.com/spf13/cobra/command.go:617 +0x2d
_/src/github.com/go-whisk-cli/commands.Execute(0x0, 0x0)
	/src/github.com/go-whisk-cli/commands/commands.go:162 +0x7fc
main.main()
	/src/github.com/go-whisk-cli/main.go:64 +0x83

goroutine 182 [syscall]:
os/signal.signal_recv(0x6)
	/usr/local/go/src/runtime/sigqueue.go:116 +0x132
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:22 +0x18
created by os/signal.init.1
	/usr/local/go/src/os/signal/signal_unix.go:28 +0x37

goroutine 183 [chan receive]:
net/http.(*Transport).dialConn(0xc8200c6000, 0x0, 0xc820051a40, 0x5, 0xc8201debe0, 0x1c, 0xc820001800, 0x0, 0x0)
	/usr/local/go/src/net/http/transport.go:837 +0x9c2
net/http.(*Transport).getConn.func4(0xc8200c6000, 0x0, 0xc820051a40, 0x5, 0xc8201debe0, 0x1c, 0xc8202029c0)
	/usr/local/go/src/net/http/transport.go:709 +0x66
created by net/http.(*Transport).getConn
	/usr/local/go/src/net/http/transport.go:711 +0x262

### PR DESCRIPTION
**Pull request by skaegi**
fixes #1352

### CODE REVIEW

**Comment by markusthoemmes** [comment]
@skaegi thanks for the contribution! While we can fix the commits in the rebase/merge phase, please review our [git guidelines](https://github.com/openwhisk/openwhisk/wiki/Contributing:-Git-guidelines) for future pull-requests. We use a `git rebase` based model rather than merge-commits.

@dubeejw seems like this supersedes #1111, what do you think?

**Comment by skaegi** [comment]
@markusthoemmes -- re: rebase instead of merge -- Sure... do you want me close and re-submit a new PR for this?

**Comment by markusthoemmes** [comment]
@skaegi no need to do that, you can just rebase and force push to this branch. It'll get rid of the merge commit.

**Comment by mdeuser** [comment]
@dubeejw - Did all of your preliminary Go 1.7 testing with the CLI pass?  Apparently, the latest Mac release requires a move to Go 1.7.

**Comment by skaegi** [comment]
@dubeejw I'm not sure if that question was directed at me. 
I can provide a data point at least -- I've been preparing a demo using the 1.7 version over the week-end and have been putting together custom packages, binding them, creating triggers, rules, and actions etc. as well as testing them and running ```wsk activation poll``` for a few days -- no crashes and no problems so far.

**Comment by dubeejw** [comment]
@mdeuser, all the tests passed, but I ran all the tests for the CLI that was compiled with Go 1.7 over a month ago. Probably wouldn't hurt to run all the automated tests again.

**Comment by csantanapr** [comment]
rebase and merged 3ae89ca7611e2ab2a932cbdd5b9351a92d21a4d2

**Pull request closed without merging**
