### PR TITLE
Use ansible 2.0.2.0 as the version to install openwhisk

### PR DESCRIPTION
**Pull request by houshengbo**
Closes-Bug: #967

### CODE REVIEW

**Comment by rabbah** [comment]
In https://github.com/openwhisk/openwhisk/issues/530 the change was made to relax the installed version of ansible and in https://github.com/houshengbo/openwhisk/commit/7ab9a47c8c17cfa0adbd0549c5b66bcb601871f9#diff-eb553454a207e03d414e88d99e504148 the installed ansible was done via apt-get instead of pip (because "pip install on vagrant requires lots of dev packages as it wants to compile deps. we don't want that.").

so we may want to install both via apt-get but install a version earlier than the latest which was just released.

@csantanapr @houshengbo

**Comment by rabbah** [comment]
`sudo apt-get install -y ansible=2.1.0.0-*` might be the stop gap.

**Comment by houshengbo** [comment]
vagrant is calling source all.sh under ubuntu setup. 
sudo apt-get install -y ansible=2.1.0.0-1* and 2.1.0.0-1ppa~trusty do not work well. It always shows unable to find ansible=2.1.0.0-1* or 2.1.0.0-1ppa~trusty.

pip can work well in installing 2.1.0.0.

**Comment by rabbah** [comment]
Reverted to using pip.

Merged as https://github.com/openwhisk/openwhisk/commit/36ad900f7a81cb835e732529a5f0a69429067dd3.

**Pull request closed without merging**
