### PR TITLE
Disable Trigger Test that uses Prop file

### PR DESCRIPTION
**Pull request by dubeejw**
- Disable test that is using the property file to set the auth key

### CODE REVIEW

**Comment by dubeejw** [comment]
Disable this test until I have time to fix/update it as it seems to be failing in Jenkins.

**Comment by dubeejw** [comment]
@mdeuser, please merge after review.

**Comment by mdeuser** [comment]
@dubeejw - travis passed, but PR is now out-of-date; please rebase.

**Comment by dubeejw** [comment]
@mdeuser, ready now.

**Pull request merged**
