### PR TITLE
Add notice about explicit passing in action sequence

### PR DESCRIPTION
**Pull request by hassenius**
Add some clarification of the unix pipe like behaviour of action sequence.

### CODE REVIEW

**Comment by hassenius** [comment]
I know there's an ongoing discussion on this topic: https://github.com/openwhisk/openwhisk/issues/116 but in the meantime the current situation should be made very clear to users.

**Comment by csantanapr** [comment]
Hi @hassenius we are happy for you taking the time to send a PR to contribute to the project. Would you mind submitting a CLA, instructions can be found here: https://github.com/openwhisk/openwhisk/blob/master/CLA-INDIVIDUAL.md

**Comment by csantanapr** [comment]
@rabbah please review text, and merge. @hassenius works IBM and don't need to signed a CLA

**Comment by rabbah** [comment]
Explanation tweaked slightly and merged as https://github.com/openwhisk/openwhisk/commit/e2a148a7ed7ad9b458cae1bb8aa26deb2af6cc00. Thanks for the contribution.

**Pull request closed without merging**
