### PR TITLE
The test should be moved into another package

### PR DESCRIPTION
**Pull request by fxulusoy**
"show api build using http apihost" test in WskBasicTests is failing.

### CODE REVIEW

**Comment by rabbah** [comment]
This test was specifically added to test http. Hence we should just move it to a different package.

**Comment by fxulusoy** [comment]
@rabbah if it is not okay to ignore for now or where can I move it?

**Comment by rabbah** [comment]
suggest establishing new package `whisk.cli` and move it there - if looking for expedient solution then just ignore and we'll move it later.

**Comment by fxulusoy** [comment]
@rabbah Let's ignore for now.

**Pull request merged**
