### PR TITLE
double default timeout for docker operations

### PR DESCRIPTION
**Pull request by sjfink**

### CODE REVIEW

**Comment by csantanapr** [comment]
@sjfink could you also update line https://github.com/openwhisk/openwhisk/blob/master/docker.gradle#L12

"* - dockerTimeout (optional, default 240): Timeout for docker operations in seconds"

**Comment by csantanapr** [comment]
running a PG build applicable for the change applicable for this one?

**Comment by sjfink** [comment]
> @sjfink could you also update line https://github.com/openwhisk/openwhisk/blob/master/docker.gradle#L12

Done.

Rebased and pushed.

I don't think we need a PG build for this one.

**Comment by csantanapr** [comment]
That's what I thought

**Comment by csantanapr** [comment]
merged #452

**Pull request closed without merging**
