### PR TITLE
additional python packages in base image for python actions

### PR DESCRIPTION
**Pull request by rabbah**
adds python packages suggested by @psuter with additional tests.

pg2-84 approved.
replaces #1192

### CODE REVIEW

**Comment by markusthoemmes** [comment]
Do we really need to test all the packages we include? My initial tests idea was to verify that the installation with `pip` works as intended. I'ld think that's sufficient. We don't do it for node.js either.

**Comment by csantanapr** [comment]
Let's ping a specific version for this packages and also need to be documented for users which version of Python it's installed along side which packages with respective versions

**Comment by rabbah** [comment]
It was primarily to make sure we don't accidentally remove a dependence after pip install.

**Comment by psuter** [comment]
Merged as 313c67174980df4e19af65c38388c69dfad69d11

**Pull request closed without merging**
