### PR TITLE
Add group-parameter to couch-view-execution

### PR DESCRIPTION
**Pull request by cbickel**
Signed-off-by: Hoang Anh Le <hoang@de.ibm.com>

PG1#565 is running

### CODE REVIEW

**Comment by cbickel** [comment]
Test is added and PG2#386 is started.

**Comment by cbickel** [comment]
PG2#402 is green

**Comment by cbickel** [comment]
PG2#411 running

**Comment by rabbah** [comment]
I tightened the tests and merged as https://github.com/openwhisk/openwhisk/commit/1be490b498239482ccca17be28e66b32e30b630e.

**Pull request closed without merging**
