### PR TITLE
Enable Colors/Styles in the CLI for Windows OS, and Add Uniform Color/Sytle Support Across Commands

### PR DESCRIPTION
**Pull request by dubeejw**
- Updating printing of colors and styles so they are displayed on the Windows operating system
- Ensure that printing of colors, and styles is uniform across commands
- Fix logo display on Windows/Mac

### CODE REVIEW

**Comment by markusthoemmes** [comment]
Why is this one needed?

**Comment by psuter** [comment]
(Sorry if this has been brought up before.) Could we check if the output is a terminal and use colors then?

**Comment by dubeejw** [comment]
Fixes https://github.com/openwhisk/openwhisk/issues/947

**Comment by markusthoemmes** [comment]
I do agree with @psuter. Can we implement a check? Python CLI used to have that.

**Comment by dubeejw** [comment]
No check necessary. I made modifications to print colors/styles in Windows.

**Comment by dubeejw** [comment]
PPG 905.

**Comment by mdeuser** [comment]
@markusthoemmes @psuter  - If the python CLI did not have this check, would some of the automated tests have failed?   In the Go CLI case, the automated tests have not been failing, so I'm wondering if that is sufficient enough validation that the Go CLI output does not include the special terminal code characters when invoked outside a terminal window.

**Comment by dubeejw** [comment]
The package we are using disables colors if a non-terminal is used.

**Comment by csantanapr** [comment]
rebase and merge f1af1fb586322d60583c3fb3daf882506a0d8de0
PG1  75

**Pull request closed without merging**
