### PR TITLE
Creating an Action with --lib is Not Supported

### PR DESCRIPTION
**Pull request by dubeejw**
- Remove defunct functionality from Go CLI

### CODE REVIEW

**Comment by mdeuser** [comment]
LGTM

**Comment by dubeejw** [comment]
@csantanapr, ready for merge.

**Comment by csantanapr** [comment]
PG please

**Comment by dubeejw** [comment]
There are no tests for the --lib flag.

**Comment by csantanapr** [comment]
assigned when PG number is provided.

**Comment by dubeejw** [comment]
The Go CLI is not tested currently, but I will run the tests anyway.

**Comment by dubeejw** [comment]
IPG 223.

**Comment by csantanapr** [comment]
rebase and merged 659fd347c4e15a0a68862e2bc6ca3c5e33659c2a

**Pull request closed without merging**
