### PR TITLE
Flip CLI Test Suite Switches to Use Go CLI

### PR DESCRIPTION
**Pull request by dubeejw**
- Flip switches for CLIActionTests, CLIJavaTests, CLIPythonTests,
  CLIRuleTests, CLISequentialTests

### CODE REVIEW

**Comment by dubeejw** [comment]
Please review.

**Comment by rabbah** [comment]
PG of course.

**Comment by dubeejw** [comment]
@rabbah, http://whiskjenkins.sl.cloud9.ibm.com:8080/job/irisPlayground/215/.

**Comment by dubeejw** [comment]
@rabbah, IPG #215.

**Comment by dubeejw** [comment]
Ready for merge.

**Comment by rabbah** [comment]
Travis failed.

**Comment by rabbah** [comment]
Rebased and merged as https://github.com/openwhisk/openwhisk/commit/4874e5703ff66180e2b5cdf148a675b8514bc7a3.

**Pull request closed without merging**
