### PR TITLE
Address issue #394 (RSS feed)

### PR DESCRIPTION
**Pull request by lzbj**
A package which can subscribe to RSS feed and generate events.

### CODE REVIEW

**Comment by markusthoemmes** [comment]
The subscription will be happening for the maximum runtime of the action only if I understand correctly?

**Comment by rabbah** [comment]
This is the action, no installation etc? Is that intentional? Also, should this be part of openwhisk or its own rss whisk package?

**Comment by csantanapr** [comment]
This is an action, that tries to read from an rss feed? Like @markusthoemmes said this is an action that get's killed by the time it tries to do something.

I don't think this is the goal, the goal is to provide a way to provide a openwhisk feed that it's implemented as a long running deamon/app that users can create triggers with configurations options like the url, they want their trigger to be fire when there is a new rss item added to the rss feed.

**Comment by lzbj** [comment]
@markusthoemmes ,thank you. @rabbah, yes, correct, just a confirm of requirements. I'll add more implementations as commented by Carlos if I could. Now I'm more clear, Thank you.
@csantanapr , do you know if there is a sample you described that could create the daemon? for the github webhook.js seems delegate the job to github?

**Comment by csantanapr** [comment]
@lzbj We don't have examples or docs yet explaining this type of feeds, but we are working on getting them available.
See #559 it contains some background and initial draft for the docs.
Examples of deamon that implements a feed are things like alarm and cloudant changes, which should be in openwhisk soon #336 #390

**Comment by lzbj** [comment]
@csantanapr, thanks a lot.

**Pull request closed without merging**
