### PR TITLE
Fixes issue 843

### PR DESCRIPTION
**Pull request by rabbah**
@fxulusoy want to give this a try? 
@domdom82 @lehoanganh please review - I added the essential bits from the prereq playbook.

### CODE REVIEW

**Comment by fxulusoy** [comment]
@rabbah I have tried many reboots, pause/start vm and it works. The changes LGTM

**Comment by domdom82** [comment]
looks ok although it has the downside of managing the prereqs in two places now. if we up the version or add more packages, we must not forget to update the tweak script, too. on the other hand I don't see any other way without tainting the common ansible playbooks with `if mac then xxx` exceptions.

**Comment by rabbah** [comment]
valid point - I'm biased toward convenience. The playbook is still valid and it's harmless to rerun even if the tweak is applied. With automated testing for the docker machine (or with docker native for max) this might become moot.

**Comment by fxulusoy** [comment]
Merged. https://github.com/openwhisk/openwhisk/commit/ea03638fa2106bafe1b313f4b34e8fd4831bd702

**Pull request closed without merging**
