### PR TITLE
Lock travis to docker 1.10.3

### PR DESCRIPTION
**Pull request by perryibm**

### CODE REVIEW

**Comment by perryibm** [comment]
This did NOT work....

**Comment by domdom82** [comment]
we are probably overriding the travis docker with our apt-get install docker-engine stuff. 

pinning using apt-get install docker-engine=1.10.3-0~trusty should work

**Comment by jeremiaswerner** [comment]
what would be the fix to support docker 1.11?

**Comment by perryibm** [comment]
Retesting with updated apt-get.

**Pull request closed without merging**
