### PR TITLE
testEcho() works with Python 2 and Python 3

### PR DESCRIPTION
**Pull request by cclauss**
Also changed `main(dict)` to `main(args)` to avoid clobbering the built-in type `dict`

### CODE REVIEW

**Comment by rabbah** [comment]
@cclauss is this ready?

**Comment by cclauss** [comment]
Yes, please.

**Comment by rabbah** [comment]
PG2/1​15​5 pending.

**Comment by cclauss** [comment]
This change was migrated into https://github.com/openwhisk/openwhisk/pull/1903

**Pull request closed without merging**
