### PR TITLE
Bump ansible to 2.3, docker (for python) to 2.2.1

### PR DESCRIPTION
**Pull request by markusthoemmes**
Ansible 2.2 fixes a couple of annoying issues, mainly a wrong version checking with docker-py. This puts us back on the latest docker-py which is desirable for future features to come (user namespaces etc.)

### CODE REVIEW

**Comment by csantanapr** [comment]
@markusthoemmes Do we need to update the other environments also?

ubuntu/vagrant:
https://github.com/openwhisk/openwhisk/blob/master/tools/ubuntu-setup/ansible.sh#L5
>sudo pip install ansible==2.1.2.0
sudo pip install docker-py==1.9.0

https://github.com/openwhisk/openwhisk/blob/master/tools/macos/README.md
># install ansible
sudo -H pip install ansible==2.1.2.0

https://github.com/openwhisk/openwhisk/blob/master/ansible/roles/prereq/tasks/deploy.yml#L16
>name: install docker-py
  pip: 
    name: docker-py
    version: 1.9.0
  become: true

**Comment by markusthoemmes** [comment]
@csantanapr of course we do, that's why the PR is still in WIP. I only switched travis to see if it goes through. The rest will follow.

**Comment by csantanapr** [comment]
@markusthoemmes thanks for the clarification

**Comment by csantanapr** [comment]
@markusthoemmes LGTM want me to merge it?

**Comment by rabbah** [comment]
bump. status?

**Comment by csantanapr** [comment]
@markusthoemmes feel free to merge when you think is ready

**Comment by markusthoemmes** [comment]
@csantanapr @rabbah pushed to the latest version of ansible, which also includes a move from `docker-py` to `docker` (renamed). The docker lib had a major version update, moving seems desirable for future compatibility.

**Comment by markusthoemmes** [comment]
PG1 1462 🔵

**Pull request merged**
