### PR TITLE
Fix cli parsing floating point number issue.

### LINKED ISSUE #1717: cli parsing of numbers to floating point considered suprising
## Environment details:
I'm running `wsk trigger create...` command on Mac CLI.

## Steps to reproduce the issue:
When I passed in `-p clientId '12345.231452'`, the parameter in the trigger would be rounded to 12345.231.
But when I passed in `-p clientId 'a12345.231452'`, I would get the expected value: `a12345.231452`.
Seems like OW is converting the parameters as floating points and rounding them?

### PR DESCRIPTION
**Pull request by lzbj**
Fixes #1717.

### CODE REVIEW

**Comment by dubeejw** [comment]
@lzbj, please run a PG.

**Comment by rabbah** [comment]
Needs a test?

**Comment by lzbj** [comment]
Thank you @dubeejw, seems I don't have rights to run PG now, I'll work with Vincent try to figure out.
@rabbah , I added a test data with current test case, is it sufficient? Thanks.

**Comment by dubeejw** [comment]
PG1 1135

**Comment by dubeejw** [comment]
PG2 1024

**Comment by dubeejw** [comment]
@lzbj, please get access for PGs. I am seeing 30+ failures when running this PR through a PG.

**Comment by lzbj** [comment]
@dubeejw ,thanks for helping me run the PG, after look the test fail log, I found mainly authentication failed related errors:

for example:

org.scalatest.exceptions.TestFailedException: 502 did not equal 200

error: Unable to delete action: A request was made of a resource using a request method not supported by that resource; (code 1227)
exit code: 149 was not equal to 0

is these errors related to the code change, I'm a little confused.

**Comment by dubeejw** [comment]
Please rebase.

**Comment by dubeejw** [comment]
Also, did you get access to PGs?

**Comment by lzbj** [comment]
Yes, rebased. I can access the PG server, just can't run any PG.

**Comment by dubeejw** [comment]
@lzbj, I believe @jeremiaswerner can help you get access to PGs.

**Comment by dubeejw** [comment]
PG3 288 is approved.

**Comment by dubeejw** [comment]
LGTM. @csantanapr, ready for merge.

**Comment by lzbj** [comment]
Ok, thank you @dubeejw , I'll ask for his help.

**Comment by rabbah** [comment]
Resolved conflict and merged as https://github.com/openwhisk/openwhisk/commit/03e041c416e19283cf1e1f2b58da85687c0c8dd5.

**Pull request closed without merging**
