### PR TITLE
WIP - Create test util method to get VCAP username and password

### PR DESCRIPTION
**Pull request by jasonpet**

### CODE REVIEW

**Comment by csantanapr** [comment]
@rabbah please handle the merge

**Comment by markusthoemmes** [comment]
It appears to me, that this and #443 are basically the same thing. Is there the possibility to deduplicate? Could we just return the "credentials" object and get the values we need directly in the test?

**Comment by rabbah** [comment]
An alternative is for one method that accepts a vararg String... Which is the map properties to add and return. I think this leads to least duplication?

**Comment by nwspeete-ibm** [comment]
Closing will deliver on #443

**Pull request closed without merging**
