### PR TITLE
Accept query doc as JSON object rather than serialized String

### PR DESCRIPTION
**Pull request by psuter**
Avoids potential double-encoding.

### CODE REVIEW

**Comment by csantanapr** [comment]
@psuter What uses this class? Maybe this is a class that doesn't belong in open and it's for internal use?
Was not able to find any references to this code in the repo.

**Comment by csantanapr** [comment]
Only applicable to cloudant? Or it works with CouchDB also?

**Comment by psuter** [comment]
The class is useful if you write a client to retrieve tailored information out of a database.

**Comment by csantanapr** [comment]
@rabbah please review and merge.

**Comment by rabbah** [comment]
Merged as https://github.com/openwhisk/openwhisk/commit/f33437a6f9dc9d775114cc1f269de5cf1c19d54f.

**Pull request closed without merging**
