### PR TITLE
Add marker for /init to analyse performance and ident…

### PR DESCRIPTION
**Pull request by jeremiaswerner**
…ify cold starts

### CODE REVIEW

**Comment by rabbah** [comment]
@jeremiaswerner you'll need to rebase and resolve conflicts for this branch.

**Comment by jeremiaswerner** [comment]
@rabbah thanks for the hint. I've resolved the merge conflict and rebased

**Comment by jeremiaswerner** [comment]
PG1-1131
PG2-1​01​4

**Comment by jeremiaswerner** [comment]
PGs greenish @rabbah @markusthoemmes pls finally review and merge.

**Comment by jeremiaswerner** [comment]
```
[2017-02-06T12:00:51.845Z] [INFO] [#tid_13] [Invoker] sending arguments to ... container [...] [...] [192.168.0.4:8080] [marker:invoker_activationRun_start:1676]
[2017-02-06T12:00:51.869Z] [INFO] [#tid_13] [Invoker] running result: ok [marker:invoker_activationRun_finish:1700:22]
```

**Comment by markusthoemmes** [comment]
rebased and merged in d47e39fb61f3e970f569a37a8713ad342ac38825

**Pull request closed without merging**
