### PR TITLE
Flip the catalog installation to the openwhisk-catalog repo

### PR DESCRIPTION
**Pull request by houshengbo**
Currently, all the actions in openwhisk-catalog have been synchronized
with the ones in openwhisk. The test coverage of actions is equal to
openwhisk. We are technically able to switch from openwhisk/catalog to the
openwhisk-catalog.

### CODE REVIEW

**Comment by houshengbo** [comment]
@rabbah @jasonpet @csantanapr 
I think the openwhisk-catalog is ready, this PR can be the first step to switch to openwhisk-catalog. After this one, actions can be removed gradually in openwhisk, and test cases will be changed accordingly.

**Comment by jasonpet** [comment]
@houshengbo - other builds outside of travis run these tests as well.  If you change the package name of the tests from util to utils these others builds, which will not be flipped as part of this PR will fail.  Please contact me via slack if you do not now about the other builds I am referring to.  In my opinion these tests either need to move to the openwhisk-catalog repo or install the actions themselves via files in the tests/dat/actions folder.  That way tests in open would not need to depend on openwhisk-catalog being installed.

**Comment by jasonpet** [comment]
@houshengbo - I created a fix for WskActionSequenceTests.  You can pull my commit:
https://github.com/jasonpet/openwhisk/commit/260e5b346b420a6ab74ae35b2c6655054758d87c

**Comment by houshengbo** [comment]
@jasonpet Thank you. I have pulled the branch and update this PR.
I will continue to fix the WskBasicTests.

**Comment by houshengbo** [comment]
@jasonpet @csantanapr @rabbah 

I found out that test cases tests/src/system/basic/WskBasicTests.scala are different from in  tests/src/system/basic/WskActionSequenceTests.scala. 

I was trying to creating the action before calling the actions themselves, but I did  not succeed.
wskprops uses the guest auth key and "_" as the namespace. If I manually change it into the system auth key and whisk.system as the namespace, it tells me I am unable to create the action, since HTTP only expects "GET"; if I contribute to use the guest auth key and the namespace "_", I can still delete the action even if I change the auth key to something else. I am unable to create the valid test case for 
```
    it should "reject deleting action in shared package not owned by authkey" in {
        wsk.action.get("/whisk.system/util/cat") // make sure it exists
        wsk.action.delete("/whisk.system/util/cat", expectedExitCode = FORBIDDEN)
    }
```
and the similar ones.

I have not found any other ways to do it except changing util to utils, because we change this name in catalog repos. I am not sure if we are OK with this approach so far.

**Comment by csantanapr** [comment]
I don't follow `HTTP only expects "GET"`  ?
when the cut is done, tests should not depend on artifacts (catago/system) to be installed first. 
The openwhisk runtime should not depend on a catalog to be installed to be able to work correctly. 
Looking at the tests cases it look they belong to in openwhisk and not catalog.
You will need to configure the tests to install a dummy/fixture package to be able to run the basic tests that verify that an user can't delete or modify a shared package without having the correct auth key. For the sequences it's just testing that sequences can be created with actions and the the sequence can be executed correctly, also can be fixture actions it's not important the functionality of the actions, but that they can be chained usable by tests.

I would suggest get together with @jasonpet or @bjustin-ibm they are familiar with the test utilities classes, there might be a need to create some helper classes to install/uninstall system packages as fixtures to be use by the test cases.

**Comment by houshengbo** [comment]
Sorry, I messed up this one. No idea why it is not updated after I submit new patches.

**Pull request closed without merging**
