### PR TITLE
Add `action update` test that expects failure when missing file is specified

### PR DESCRIPTION
**Pull request by mdeuser**
Add `action update` test that expects failure when missing file is specified

### CODE REVIEW

**Comment by mdeuser** [comment]
@dubeejw - Ready for review.  All tests for both python and Go passed locally.

**Comment by dubeejw** [comment]
@csantanapr, please merge.

**Comment by rabbah** [comment]
give me a chance to review please.

**Comment by csantanapr** [comment]
@mdeuser PG please.
@rabbah assigned to you when PG pass and you OK the review.

**Comment by rabbah** [comment]
Rebased and merged as https://github.com/openwhisk/openwhisk/commit/d2d241bd2ce9521c793fe6594bb4248f0076169c.

**Pull request closed without merging**
