### PR TITLE
Remove Swift SDK Placeholder

### PR DESCRIPTION
**Pull request by dubeejw**
- Remove references to the Swift SDK from the CLI

Fixes: https://github.com/openwhisk/openwhisk/issues/1173
PG2: 105

### CODE REVIEW

**Comment by bjustin-ibm** [comment]
@dubeejw I was going to ask if there shouldn't be a test that needs updating as a result of this, but then Travis answered that for me:

```
system.basic.WskSdkTests > Wsk SDK should preview swift sdk STANDARD_OUT
    expected exit code = 0
    exit code = 1
    stdout: 
    stderr: error: The SDK component argument 'swift' is invalid. Valid components are docker, ios and bashauto
    Run 'wsk --help' for usage.


system.basic.WskSdkTests > Wsk SDK should preview swift sdk FAILED
```

**Comment by bjustin-ibm** [comment]
Otherwise this LGTM. It is a real bummer though that information about the valid SDKs is repeated so much...

**Comment by dubeejw** [comment]
@bjustin-ibm, the unneeded Swift SDK test case has been removed.

**Comment by bjustin-ibm** [comment]
Rebased and merged as 8eacc173b85f4ded8fdefc94cb1451eb8c94256c

**Pull request closed without merging**
