### PR TITLE
[WIP]: Remove the catalog installation and the tests

### PR DESCRIPTION
**Pull request by houshengbo**
This patch targets to remove the catalog installation from OpenWhisk,
and the tests for them, so that OpenWhisk will not install catalog
by default. Instead, the tests need to be created in OenWhisk-catalog,
which is hosting the new location for all the catalog.

Partial-Closes-Bug: #748

### CODE REVIEW

**Comment by houshengbo** [comment]
@csantanapr Yes.
I am narrowing down the scope for the tests now into:
```
#       deleted:    tests/src/packages/SamplesTests.java
#       deleted:    tests/src/packages/SlackTests.java
#       deleted:    tests/src/packages/UtilsTests.scala
#       deleted:    tests/src/packages/websocket/WebSocketTests.scala
#       **deleted:    tests/src/services/HeadersTests.scala**
#       deleted:    tests/src/system/basic/CLIActionTests.java
#       deleted:    tests/src/system/basic/CLIJavaTests.scala
#       deleted:    tests/src/system/basic/CLIPythonTests.scala
#       deleted:    tests/src/system/basic/CLIRuleTests.java
#       deleted:    tests/src/system/basic/CLISequentialTests.java
#       deleted:    tests/src/system/basic/CLISwiftTests.scala
#       deleted:    tests/src/system/basic/ConsoleTests.scala
#       deleted:    tests/src/system/basic/PackageTests.scala
#       deleted:    tests/src/system/basic/Swift3WhiskObjectTests.scala
#       deleted:    tests/src/system/basic/WskActionSequenceTests.scala
#       deleted:    tests/src/system/basic/WskBasicTests.scala
#       deleted:    tests/src/system/rest/ActionSchemaTests.scala
#       **deleted:    tests/src/whisk/core/container/test/ContainerPoolTests.scala**
```

I still need to look at HeadersTests.scala and ContainerPoolTests.scala, because they are not quite related to catalog, but will fail without catalog installation.

**Comment by rabbah** [comment]
There are several of these that should NOT be moved. Anything in whisk/core should not move. Anything in system/baisc should not be moved. If these tests fails without catalog, then they should be made to work (by adding whatever assets they need to the tests/dat directory and creating the required assets as part of the test harness).

**Comment by rabbah** [comment]
May I suggest that instead of whole sale moving packages and tests suites that you do this incrementally? Move exactly 1 package and its corresponding suite at a time. You''ll be thankful later to do it this way.

**Comment by houshengbo** [comment]
@rabbah @csantanapr 
There are many test cases in system/basic related to the actions created by installCatalog. They will fail when openwhisk does not install the catalog. Since all the catalog is moved to openwhisk-catalog, the test cases deleted here in openwhisk, will be available in openwhisk-catalog. 

I will keep this PR alive, because openwhisk-catalog can refer to it for empty catalog. 
I can do the deletion of catalog incrementally.

**Comment by markusthoemmes** [comment]
We should not lose most of the tests you pointed out. They should rather be refactored to not rely on the catalog anymore (for the ones it makes sense obviously)

**Comment by rabbah** [comment]
@houshengbo this seems like it should be combined with you other pr #720.

**Comment by houshengbo** [comment]
Let me close it first. I will come up a new script when openwhisk-catalog is reliable enough.

**Pull request closed without merging**
