### PR TITLE
Adding documentation on gradle usage

### PR DESCRIPTION
**Pull request by markusthoemmes**

### CODE REVIEW

**Comment by rabbah** [comment]
@csantanapr good idea - but is that a separate pr? as you point out there are many of these docs are dev only scatttered through out.

**Comment by csantanapr** [comment]
>@csantanapr good idea - but is that a separate pr?

Good point lets keep moving forward 🚆

**Comment by csantanapr** [comment]
I can take care of the index and location in later PR

**Comment by csantanapr** [comment]
merged 601da30ebcd5afc4563275ab5fc9f7fe8df9297b

**Pull request closed without merging**
