### PR TITLE
Ignore the .zip files generated during deployment of routemgmt actions

### PR DESCRIPTION
**Pull request by mdeuser**

### CODE REVIEW

**Comment by mdeuser** [comment]
PG1 1125

**Comment by markusthoemmes** [comment]
Just wanted to do the same. I ended up with the following

```
commit 3060c9d2f1276d556d70430707a7677ddae34e13
Author: Markus Thoemmes <markus.thoemmes@de.ibm.com>
Date:   Wed Feb 1 16:54:34 2017 +0100

    Adding zip files to gitignore

diff --git a/.gitignore b/.gitignore
index 57884eec..b518b36a 100644
--- a/.gitignore
+++ b/.gitignore
@@ -51,3 +51,8 @@ ansible/roles/nginx/files/*cert.pem
 # Action proxies copied during build
 core/swiftAction/actionproxy.py
 core/swift3Action/actionproxy.py
+
+# Zips in tests whitelisted
+*.zip
+tests/dat/actions/zippedaction.zip
+tests/dat/actions/blackbox.zip
```

**Comment by csantanapr** [comment]
Yeah I prefer @markusthoemmes approach no zips in source control, unless it's some type required test fixture.

@mdeuser can you adjust ?

**Comment by mdeuser** [comment]
sure. here's what i have now:
```
# .zip files must be explicited whitelisted
*.zip
!tests/dat/actions/blackbox.zip
!tests/dat/actions/zippedaction.zip
```

**Comment by mdeuser** [comment]
PG1 1127

**Pull request merged**
