### PR TITLE
update documentation of throttling limits

### PR DESCRIPTION
**Pull request by sjfink**

### CODE REVIEW

**Comment by csantanapr** [comment]
Fixes #1365

**Comment by rabbah** [comment]
As noted in the issue, the limits documented here are specific to bluemix and not local development.

**Comment by csantanapr** [comment]
So it means this PR is invalid on this repo then

**Comment by csantanapr** [comment]
I see we removed the hour limit, is this true only for bluemix but not for openwhisk?

**Comment by rabbah** [comment]
no more hour limit anywhere.

**Comment by csantanapr** [comment]
Can we make the limits the same?
I know we have throttle tests, but they are unreliable anyway they failed a lot

**Comment by markusthoemmes** [comment]
The limits are configurable for anyone deploying OpenWhisk. Those tests would 1. take muuuuuch longer and 2. be way more unreliable with the same limits configured everywhere. It's not sustainable to test the same limits in dev envs. as in highly scalable prod. envs.

**Comment by csantanapr** [comment]
Maybe the tests need to be disable by default and only to be use in a system integration test with were there could be more control over the environment.

In a dev environment functional tests are the ones that are most important, testing limits come into play when deploying into a test or production environment, not when doing local development I should not have any limits when I run OpenWhisk in my laptop.

We could set the limit only for travis and keep running the tests only in travis CI.

**Comment by rabbah** [comment]
These tests are the equivalent of a mini load test - they can exhibit some pathologies even with reduced limits that are important to test when working on the invoker. We should not exclude them for local development.

**Comment by csantanapr** [comment]
this one was superseded by #1376

**Pull request closed without merging**
