### PR TITLE
Adding two mirrors of tinycorelinux if the default repo is down

### PR DESCRIPTION
**Pull request by fxulusoy**

### CODE REVIEW

**Comment by rabbah** [comment]
should we add these mirrors automatically as part of the tweaking script?

**Comment by csantanapr** [comment]
@fxulusoy I agree with @rabbah 
I think it will be better to address the problem in the script tweak-dockermachine.sh
by adding the mirror, or just ping which repo is up and use that one.

**Comment by csantanapr** [comment]
bump @fxulusoy

**Comment by fxulusoy** [comment]
@csantanapr I will add the mirrors  in the script tweak-dockermachine.sh

**Comment by csantanapr** [comment]
rebase and merged 83227e2ee617965e1208f67a12bed2de96f37ba0

**Pull request closed without merging**
