### PR TITLE
Reading old invoker state upon startup

### PR DESCRIPTION
**Pull request by markusthoemmes**
This is intended to be a stop-gap solution to make the Invoker restartable until the new algorithm by @perryibm is in place.

### CODE REVIEW

**Comment by perryibm** [comment]
Thanks - consul work still in queue but getting bumped.   For this temp fix, has it been tested with an actual restart?   Regular PG won't test this I think.

**Comment by markusthoemmes** [comment]
Well yeah, i tried locally and it counted from the state where it left of.

**Comment by perryibm** [comment]
227 was not clean - retrying PG2 232

**Comment by markusthoemmes** [comment]
PG1 526 was fine.

**Comment by perryibm** [comment]
rebase/merged

**Pull request closed without merging**
