### PR TITLE
Disable HTML Encoding of JSON Content in CLI

### PR DESCRIPTION
**Pull request by dubeejw**
- Do not encode &, <, and > to \u0026, \u003c, and \u003e
- Prevents mentioned characters in raw HTTP web action query parameters from being encoded in activation logs

### CODE REVIEW

**Comment by dubeejw** [comment]
@rabbah, needs review.

**Comment by dubeejw** [comment]
PG3 423.

**Comment by dubeejw** [comment]
PG2 1254 approved.

**Comment by dubeejw** [comment]
@rabbah, this will fix the log issue.

**Comment by rabbah** [comment]
should we extend one of the tests to assert?

**Comment by dubeejw** [comment]
@rabbah, do you see anything wrong with the test I added? Looks like a container isn't starting for the test's action. Here's the error:

```
whisk.core.cli.test.WskBasicUsageTests > Wsk actions should invoke action while not encoding &, <, > characters STANDARD_OUT
    check failed for activation 37633225ad5d4b00bd27c53f21002481: 
{
  "duration":0,
  "name":"nonescape",
  "subject":"guest",
  "activationId":"37633225ad5d4b00bd27c53f21002481",
  "publish":false,
  "annotations":
  [
    {
    "key":"limits",
    "value":
      {
        "logs":10,
        "memory":256,
        "timeout":60000
      }
    },
    {
      "key":"path",
      "value":"guest/nonescape"
    }
  ],
  "version":"0.0.1",
  "response":
  {
    "status":"whisk internal error",
    "statusCode":0,
    "success":false,
    "result":
    {
      "error":"Failed to start container."
    }
  },
  "end":1490050166105,
  "logs":[],
  "start":1490050166105,
  "namespace":"guest"
  }
```

**Comment by dubeejw** [comment]
PG2 1286 approved.

**Pull request merged**
