### PR TITLE
Test retries.

### PR DESCRIPTION
**Pull request by rabbah**
Wrap API tests on list operations with retry for eventual consistency.

### CODE REVIEW

**Comment by mdeuser** [comment]
LGTM.  I noticed that there are some `list` related package tests that don't have the `whisk.utils.retry` decoration.. For example `list all public packages in explicit namespace excluding bindings`.  Is retry not needed for that one?

**Comment by rabbah** [comment]
Will add it - missed them.

**Comment by rabbah** [comment]
Now covered the packages tests as well.

**Comment by rabbah** [comment]
Haven't seen this failures in some time. Going to close.

**Pull request closed without merging**
