### PR TITLE
Fix Action List Help

### PR DESCRIPTION
**Pull request by dubeejw**
- Action list displays the wrong help information

Closes https://github.com/openwhisk/openwhisk/issues/1483

### CODE REVIEW

**Comment by csantanapr** [comment]
@dubeejw I only a change for user visible string. 
Should this PR also have a change to the nls resource like en_US.all.json?

**Comment by dubeejw** [comment]
@csantanapr, the string already exists in the NLS file. The proper message was accidentally removed from the action.go file.

**Comment by csantanapr** [comment]
@dubeejw do we need a PG or travis green build is enough?

**Comment by dubeejw** [comment]
@csantanapr, there aren't any tests that examine the help information. A green Travis build should suffice.

**Comment by csantanapr** [comment]
rebase and merge 277a051b09238a299983994be6904c7a631c5741

**Pull request closed without merging**
