### PR TITLE
Fix IOS SDK and a timing bug in DispatcherTest

### PR DESCRIPTION
**Pull request by rabbah**
@paulcastro if you build the framework with the latest Swift SDK, the starter app won't build since there was a recent changed in the SDK. Can you review and check why the iOS jenkins build didn't catch this?

### CODE REVIEW

**Comment by paulcastro** [comment]
Yes this looks right.  I can't merge but feel free to

**Comment by rabbah** [comment]
Any idea why jenkins is blue for the ios build?

**Comment by rabbah** [comment]
PG pending.

**Comment by paulcastro** [comment]
Starter app build is done out of band from any tests

**Comment by rabbah** [comment]
PPG 868 approved.

**Pull request merged**
