### PR TITLE
relax the ssl certificate validation for test cases

### PR DESCRIPTION
**Pull request by jeremiaswerner**
This change relaxes the https certificate validation in test cases and will unblock integration testing of API gateway. Today we only accept certificates that are added to the keystore. An alternative solution is to add the certificate of the API Gateway to that keystore. However, to avoid the same issue to happen in the future and since this is only for testing purposes I'am proposing to relax the ssl handling.

### CODE REVIEW

**Comment by jeremiaswerner** [comment]
PG2/1460

**Comment by mdeuser** [comment]
I recommend only relaxing the API GW tests; I have a branch testing out a change to do just that.

**Comment by domdom82** [comment]
@jeremiaswerner oops, sorry. didn't think I had any rights to update your branch. pls remove me as a collaborator.

**Comment by jeremiaswerner** [comment]
this PR is resolved by another PR form mdeuser

**Pull request closed without merging**
