### PR TITLE
Issue #1458, update iOS starterApp FilterForecast action to work with…

### PR DESCRIPTION
**Pull request by paulcastro**
… Swift 3 runtime.  Fixes Issue #1458 

PG 781 blue-ish, PG 784.

### CODE REVIEW

**Comment by bjustin-ibm** [comment]
@paulcastro This concerns me a bit. If I understand correctly, this code compiles and runs well on the Swift 2 runtime, but not on Swift 3. If that is true, then why does the Swift 3 runtime expect a different label for the `main` function argument? Wouldn't this same change be required for _all_ actions that are being transitioned from the Swift 2 runtime?

**Comment by paulcastro** [comment]
Swift 3 started enforcing argument labels so `main(args: [String:Any])` has to be called using `main(args: ["name":"Joe"])`.  In Swift 2 you didn't have to specify the argument.  We call main in our epilogue.swift so we have to decide on the name parameter.

I recall a proposal for Swift 3 that dropped the argument labels entirely when calling a function but I don't see that in the current release.

**Comment by bjustin-ibm** [comment]
ah... I see now. So this code was using `params` as the label (and possibly getting away with it) when we have been suggesting the `args` label all along. My only concern was if there were lots of existing Swift 2 actions that were using `params`, but that does not actually seem to be the case.

Thanks for clarifying.

**Comment by paulcastro** [comment]
Yes, we will deprecate Swift 2 (issue #1459 )

**Pull request merged**
