### PR TITLE
WIP: Do not merge until openwhisk-catalog is robust enough. Remove the greeting action and the test cases

### PR DESCRIPTION
**Pull request by houshengbo**
For future development of actions, openwhisk-catalog will become the repo
hosting them. Vincent is currently working on the catalog movement one by
one, please reach out to him for any concerns.

### CODE REVIEW

**Comment by rabbah** [comment]
before removing, can we add? 
i.e., rather that remove test coverage, we should run both the old and the new in parallel (or control with a switch) then remove.

**Comment by houshengbo** [comment]
@rabbah there is one already in openwhisk-catalog

**Comment by jasonpet** [comment]
@houshengbo - you may have one in openwhisk-catalog, but that is not currently even being installed.  You can't remove this until the one from openwhisk-catalog is installed since we have dependencies on it.  I have an existing PR that create a new Promises sample action that invokes /whisk.system/samples/greeting

**Comment by jasonpet** [comment]
@houshengbo  - I see you are removing the tests/src/packages/SamplesTests.java file from openwhisk and I assume moving to openwhisk-catalog.  How are you handling test utility dependencies in this file such as the following:

import common.Pair;
import common.TestUtils;
import common.WskCli;

**Comment by houshengbo** [comment]
The build.gradle file in openwhisk-catalog/test will import all the test dependencies in openwhisk. openwhisk-catalog is a repo depending on openwhisk. All the dependencies openwhisk has are able to import to openwhisk-catalog now. No matter you install openwhisk-catalog or run the test cases in openwhisk-catalog, please make openwhisk is installed first.

For more detailed information about the dependencies importing, please check: https://github.com/openwhisk/openwhisk-catalog/blob/master/tests/build.gradle

**Comment by houshengbo** [comment]
For future development of actions, openwhisk-catalog will become the repo
hosting them. Vincent is currently working on the catalog movement one by
one, please reach out to him for any concerns.

**Comment by jasonpet** [comment]
@houshengbo - The problem with your current setup is that openwhisk-catalog depends on the binaries that are built as part of the openwhisk test module.  You are making the assumption that when a user

**Comment by jasonpet** [comment]
@houshengbo - I closed this since there are some big issues with the current design in how you are handling dependencies.  In response to my question above you mentioned that you are dealing with the test utility dependencies by importing them from openwhisk.  However, looking at the code it looks like you are currently resolving the dependencies by pointing to the build output binaries in openwhisk (not good).

**Pull request closed without merging**
