### PR TITLE
Watson text to speech action

### PR DESCRIPTION
**Pull request by joachimvaldez**
Signed-off-by: Jason Peterson <jasonpet@us.ibm.com>

### CODE REVIEW

**Comment by bjustin-ibm** [comment]
@joachimvaldez I just discovered that there is a full description of the Watson package in `docs/catalog.md`. You probably want to document details about the new action there.

**Comment by joachimvaldez** [comment]
Hey @bjustin-ibm. Apparently those files are generated from a private IBM repo, and you're not supposed to edit them? I'll send you the details privately.

**Comment by csantanapr** [comment]
Hi @bjustin-ibm @joachimvaldez the docs are a bit of out of sync.
You will need to update the docs here in public github [IBM-Bluemix/docs/openwhisk/openwhisk_catalog.md](https://github.com/IBM-Bluemix/docs/blob/master/openwhisk/openwhisk_catalog.md)
Then run a script to remove the IBMish metadata to with a script [transform.sh](https://github.ibm.com/BlueMix-Fabric/bluewhisk/blob/master/blue/docs/transform.sh) and then update the [openwhisk/docs/catalog.md](https://github.com/openwhisk/openwhisk/blob/master/docs/catalog.md)

We need work to doc and improve how people can easily make updates to the docs in the public

**Comment by rabbah** [comment]
@starpit: comments on the annotations, in particular the sample output?

**Comment by starpit** [comment]
this looks pretty good. i would like it if it could get:

1) field-level descriptions; e.g. payload's description would be something like "The text to verbalize"; and what is voice? a description here would help maybe linking to a doc page that gives the options, along with a sample input for voice

2) this is one case where i'd love to explore mime typing the I/O, output specifically in this case. @perryibm has suggested that we could use the browser's richer I/O capabilities; e.g. to offer the output as an audio playback widget. could we testbed this idea, here?

3) could we use this opportunity to enrich the package-level data? a) a branding annotations "IBM Watson (TM) Whatever", and an icon annotation (does Watson have one?), to start with

**Comment by joachimvaldez** [comment]
The doc for this is [here] (https://github.com/IBM-Bluemix/docs/pull/169) @rabbah

**Comment by starpit** [comment]
the sampleOutput here doesn't seem to align with the input specifications for speech-to-text..

in particular, in stt, there is a `content_type` input parameter. whereas in tts there is a metadata: { mimetype: "..." } structure. at the very least, wouldn't it be nice to have the same field names? e.g.

```
sampleOutput: { payload: xxx, encoding: "base64", content_type: "audio/wav" }
```

re: rich data, this PR has the same potential issues as with #277, the stt PR, though perhaps the issue is less egregious here. the issue is that that triple of fields really conveys one piece of data; i.e. the data values of those latter two fields are actually "runtime annotations" on a third parameter, rather than being first-class data values.

**Comment by joachimvaldez** [comment]
A problem here is that the Watson API uses "accept" for text-to-speech input, yet uses "content_type" for in speech-to-text input, and I'm mirroring the Watson API. I can, however, remove the metadata field in text-to-speech output so that it matches the input of speech-to-text (so "accept" in tts input would be the same as "content_type" in tts output). The end product would look like this:

Text to speech
```
    -a sampleInput '{"payload":"Hello, world.", "encoding":"base64", "accept":"audio/wav", "username":"XXX", "password":"XXX" }' \
    -a sampleOutput '{"payload":"<base64 encoding of a .wav file>", "encoding":"base64", "content_type":"audio/wav"}'
```

Speech to text
```
    -a sampleInput '{"payload":"<base64 encoding of a wav file>", "encoding":"base64", "content_type":"audio/wav", "username":"XXX", "password":"XXX"}' \
    -a sampleOutput '{"data":"Hello."}'
```
Anyone have objections?

**Comment by starpit** [comment]
looks good, thanks!

**Comment by csantanapr** [comment]
LGTM !

**Comment by joachimvaldez** [comment]
Ok, it has been updated.

**Comment by csantanapr** [comment]
@joachimvaldez can you rebase this PR? Github is reporting `This branch is out-of-date with the base branch`

**Comment by rabbah** [comment]
That's ok.

**Comment by rabbah** [comment]
Rebased and merged as part of this [commit](https://github.com/openwhisk/openwhisk/compare/7a5e1240c0ac...f9b4f4841543).

**Pull request closed without merging**
